"""Every place the realm can name: maps, zones, doorways and ground aims.

WHY THIS EXISTS. The site said "crossed into an unknown place" for a
character who had walked into The Deadmines, "walking to trigger 194" for a
party leaving Shadowfang Keep, and "a spot on the map" for an errand to the
Menethil Harbor docks. Each of those facts was on the row; only the name was
missing. zones.json holds the four continents and their zones and nothing
inside an instance, and acore_world's `map_dbc` table is empty (map names are
client data), so a lookup that asked only those two answered "unknown".

WHAT IT HOLDS.

  MAP_NAMES    every map of the 3.3.5 client's Map.dbc a character can stand
               on: continents, dungeons, raids, battlegrounds, arenas and the
               boats and zeppelins, by id. Frozen client data, so frozen here.
  ZONE_NAMES   zones.json's zone names are the client's directory names
               ("Ogrimmar", "Hilsbrad", "ShattrathCity"); this is what the game
               says out loud, the same table tools/gen_shapes.py draws with.
  triggers     triggers.json: every teleporting areatrigger (acore_world
               areatrigger joined to areatrigger_teleport, generated by
               tools/gen_triggers.py), with the map it stands on and the map it
               leads to.
  landmarks    taxinodes.json's flight masters ("Menethil Harbor, Wetlands")
               and DOCKS below: the town a ground aim stands in.

PURE apart from reading the committed JSON once.
"""

from __future__ import annotations

import json
import math
import os
from functools import lru_cache

HERE = os.path.dirname(os.path.abspath(__file__))

CONTINENT, DUNGEON, RAID, BATTLEGROUND, ARENA, TRANSPORT, CITY = (
    "continent",
    "dungeon",
    "raid",
    "battleground",
    "arena",
    "transport",
    "city",
)

# Map.dbc (3.3.5a), by id, as the game names each map. Test and unused maps
# are left out: no character stands on them.
_MAPS = {
    CONTINENT: {
        0: "Eastern Kingdoms",
        1: "Kalimdor",
        530: "Outland",
        571: "Northrend",
        609: "Ebon Hold",
    },
    CITY: {369: "Deeprun Tram", 449: "Champions' Hall", 450: "Hall of Legends"},
    DUNGEON: {
        33: "Shadowfang Keep",
        34: "The Stockade",
        36: "The Deadmines",
        43: "Wailing Caverns",
        47: "Razorfen Kraul",
        48: "Blackfathom Deeps",
        70: "Uldaman",
        90: "Gnomeregan",
        109: "Sunken Temple",
        129: "Razorfen Downs",
        189: "Scarlet Monastery",
        209: "Zul'Farrak",
        229: "Blackrock Spire",
        230: "Blackrock Depths",
        269: "The Black Morass",
        289: "Scholomance",
        329: "Stratholme",
        349: "Maraudon",
        389: "Ragefire Chasm",
        429: "Dire Maul",
        540: "The Shattered Halls",
        542: "The Blood Furnace",
        543: "Hellfire Ramparts",
        545: "The Steamvault",
        546: "The Underbog",
        547: "The Slave Pens",
        552: "The Arcatraz",
        553: "The Botanica",
        554: "The Mechanar",
        555: "Shadow Labyrinth",
        556: "Sethekk Halls",
        557: "Mana-Tombs",
        558: "Auchenai Crypts",
        560: "Old Hillsbrad Foothills",
        574: "Utgarde Keep",
        575: "Utgarde Pinnacle",
        576: "The Nexus",
        578: "The Oculus",
        585: "Magisters' Terrace",
        595: "The Culling of Stratholme",
        599: "Halls of Stone",
        600: "Drak'Tharon Keep",
        601: "Azjol-Nerub",
        602: "Halls of Lightning",
        604: "Gundrak",
        608: "The Violet Hold",
        619: "Ahn'kahet: The Old Kingdom",
        632: "The Forge of Souls",
        650: "Trial of the Champion",
        658: "Pit of Saron",
        668: "Halls of Reflection",
    },
    RAID: {
        249: "Onyxia's Lair",
        309: "Zul'Gurub",
        409: "Molten Core",
        469: "Blackwing Lair",
        509: "Ruins of Ahn'Qiraj",
        531: "Temple of Ahn'Qiraj",
        532: "Karazhan",
        533: "Naxxramas",
        534: "Hyjal Summit",
        544: "Magtheridon's Lair",
        548: "Serpentshrine Cavern",
        550: "Tempest Keep",
        564: "Black Temple",
        565: "Gruul's Lair",
        568: "Zul'Aman",
        580: "Sunwell Plateau",
        603: "Ulduar",
        615: "The Obsidian Sanctum",
        616: "The Eye of Eternity",
        624: "Vault of Archavon",
        631: "Icecrown Citadel",
        649: "Trial of the Crusader",
        724: "The Ruby Sanctum",
    },
    BATTLEGROUND: {
        30: "Alterac Valley",
        489: "Warsong Gulch",
        529: "Arathi Basin",
        566: "Eye of the Storm",
        607: "Strand of the Ancients",
        628: "Isle of Conquest",
    },
    ARENA: {
        559: "Nagrand Arena",
        562: "Blade's Edge Arena",
        572: "Ruins of Lordaeron",
        617: "Dalaran Sewers",
        618: "The Ring of Valor",
    },
    TRANSPORT: {
        582: "the boat from Rut'theran Village to Auberdine",
        584: "the boat from Menethil Harbor to Theramore",
        586: "the boat from the Exodar to Auberdine",
        587: "the Feathermoon ferry",
        588: "the boat from Menethil Harbor to Auberdine",
        589: "the zeppelin from Orgrimmar to Grom'gol",
        590: "the zeppelin from Grom'gol to the Undercity",
        591: "the zeppelin from the Undercity to Orgrimmar",
        593: "the boat from Booty Bay to Ratchet",
        594: "the Howling Fjord boat",
        596: "the Naglfar",
        610: "the zeppelin from Tirisfal to Vengeance Landing",
        612: "the boat from Menethil Harbor to Valgarde",
        613: "the zeppelin from Orgrimmar to Warsong Hold",
        614: "the boat from Stormwind to Valiance Keep",
        620: "the turtle boat from Moa'ki to Unu'pe",
        621: "the turtle boat from Moa'ki to Kamagua",
        622: "Orgrim's Hammer",
        623: "The Skybreaker",
        647: "the zeppelin from Orgrimmar to Thunder Bluff",
    },
}

MAP_NAMES: dict[int, str] = {
    map_id: name for table in _MAPS.values() for map_id, name in table.items()
}
MAP_KINDS: dict[int, str] = {
    map_id: kind for kind, table in _MAPS.items() for map_id in table
}

# What the game calls the zones zones.json files under their directory names.
ZONE_NAMES = {
    "Hilsbrad": "Hillsbrad Foothills",
    "Ogrimmar": "Orgrimmar",
    "Aszhara": "Azshara",
    "Darnassis": "Darnassus",
    "Stranglethorn": "Stranglethorn Vale",
    "Elwynn": "Elwynn Forest",
    "Tirisfal": "Tirisfal Glades",
    "Silverpine": "Silverpine Forest",
    "Alterac": "Alterac Mountains",
    "Arathi": "Arathi Highlands",
    "Hinterlands": "The Hinterlands",
    "Redridge": "Redridge Mountains",
    "Barrens": "The Barrens",
    "Dustwallow": "Dustwallow Marsh",
    "UngoroCrater": "Un'Goro Crater",
    "Stormwind": "Stormwind City",
    "Hellfire": "Hellfire Peninsula",
    "IcecrownGlacier": "Icecrown",
    "HrothgarsLanding": "Hrothgar's Landing",
    "ZulDrak": "Zul'Drak",
    "LakeWintergrasp": "Wintergrasp",
    "BladesEdgeMountains": "Blade's Edge Mountains",
    "Sunwell": "Isle of Quel'Danas",
}

# The docks and zeppelin towers a ground aim most often stands on, by map and
# position: each is where the world database spawns that stop's dockmaster or
# zeppelin master (acore_world.creature), and the Menethil berth the Theramore
# boat ties up at. Flight masters do not stand on piers, so a town name alone
# would put a boat errand in the middle of the town.
DOCKS = (
    (0, -3898.0, -597.0, "the Menethil Harbor docks"),
    (0, -3727.0, -577.0, "the Menethil Harbor docks"),
    (0, -8303.0, 1402.0, "the Stormwind Harbor docks"),
    (0, -8641.0, 1331.0, "the Stormwind Harbor docks"),
    (0, -12430.0, 212.0, "the Grom'gol zeppelin tower"),
    (0, 2060.0, 290.0, "the Undercity zeppelin tower"),
    (1, 1340.0, -4646.0, "the Orgrimmar zeppelin tower"),
    (1, 1160.0, -4152.0, "the Orgrimmar zeppelin tower"),
    (571, 594.0, -5105.0, "the Valgarde docks"),
    (571, 2236.0, 5129.0, "the Valiance Keep docks"),
    (571, 2818.0, 6177.0, "the Warsong Hold zeppelin tower"),
    (571, 1975.0, -6095.0, "the Vengeance Landing zeppelin tower"),
    (571, 2657.0, 892.0, "the Moa'ki Harbor docks"),
    (571, 2839.0, 4019.0, "the Unu'pe docks"),
    (571, 783.0, -2816.0, "the Kamagua docks"),
)
# How near a dock or a flight master a point must be to be named after it.
DOCK_YARDS = 80.0
TOWN_YARDS = 400.0


def map_name(map_id) -> str:
    """The map's name, as the game says it; an id this client never had is
    named as an id, with the word "map" so it is never read as a count."""
    try:
        wanted = int(map_id)
    except (TypeError, ValueError):
        return "a map the row does not name"
    return MAP_NAMES.get(wanted) or "map %d" % wanted


def map_kind(map_id) -> str:
    """continent, city, dungeon, raid, battleground, arena or transport."""
    try:
        return MAP_KINDS.get(int(map_id), "")
    except (TypeError, ValueError):
        return ""


def is_instance(map_id) -> bool:
    """A map entered through a door, which a character enters and leaves."""
    return map_kind(map_id) in (DUNGEON, RAID, BATTLEGROUND, ARENA)


def zone_display(name: str) -> str:
    """zones.json's directory name as the game says it: "Ogrimmar" is
    Orgrimmar, "ShattrathCity" is Shattrath City."""
    name = str(name or "")
    if name in ZONE_NAMES:
        return ZONE_NAMES[name]
    out = ""
    for i, ch in enumerate(name):
        if i and ch.isupper() and name[i - 1].islower():
            out += " "
        out += ch
    return out


@lru_cache(maxsize=1)
def _geometry():
    from transform import Geometry

    return Geometry.load(HERE)


@lru_cache(maxsize=1)
def triggers() -> dict:
    """trigger id -> {map, x, y, to_map, to_x, to_y}, from triggers.json."""
    with open(os.path.join(HERE, "triggers.json")) as f:
        return {int(k): v for k, v in json.load(f).items()}


_NOT_TOWNS = ("Transport", "Flavor", "Quest")


@lru_cache(maxsize=1)
def _towns() -> tuple:
    """(map, x, y, "Town (Zone)") for every flight master named "Town, Zone".

    The node's own zone is used rather than the zone rectangles', which
    overlap: the Crossroads stands inside Mulgore's rectangle.
    """
    with open(os.path.join(HERE, "taxinodes.json")) as f:
        nodes = json.load(f)["nodes"]
    out = []
    for n in nodes:
        name = str(n.get("name") or "")
        if name.count(",") != 1 or name.startswith(_NOT_TOWNS) or " - " in name:
            continue
        town, zone = (part.strip() for part in name.split(","))
        out.append((int(n["map"]), float(n["x"]), float(n["y"]), (town, zone)))
    return tuple(out)


@lru_cache(maxsize=1)
def _doors() -> tuple:
    """(map, x, y, "the door of <instance>") for every doorway into an
    instance that stands on open ground."""
    return tuple(
        (
            int(t["map"]),
            float(t["x"]),
            float(t["y"]),
            "the door of " + map_name(t["to_map"]),
        )
        for t in triggers().values()
        if not is_instance(t["map"]) and is_instance(t["to_map"])
    )


def _nearest(points, map_id: int, x: float, y: float, yards: float):
    best, best_d = None, yards
    for m, px, py, name in points:
        if m != map_id:
            continue
        d = math.hypot(px - x, py - y)
        if d <= best_d:
            best, best_d = name, d
    return best


def zone_at(map_id, x, y) -> str:
    """The zone a point stands in, as the game names it; inside an instance,
    the instance.

    zones.json's rectangles overlap (Mulgore's covers the Wailing Caverns
    door in The Barrens), so when more than one holds the point, the zone of
    the nearest flight master breaks the tie, and the smallest wins after.
    """
    map_id = int(map_id)
    if map_kind(map_id) not in (CONTINENT, ""):
        return map_name(map_id)
    x, y = float(x), float(y)
    held = _zones_holding(map_id, x, y)
    if not held:
        return zone_display(_geometry().zone_name(map_id, x, y))
    if len(held) > 1:
        town = _nearest(_towns(), map_id, x, y, float("inf"))
        # A city is a zone of its own inside its land: "Orgrimmar, Durotar"
        # stands in Orgrimmar.
        for said in town or ():
            for name in held:
                if name.startswith(zone_display(said)):
                    return name
    return held[0]


def _zones_holding(map_id: int, x: float, y: float) -> list:
    """Display names of the zone rectangles holding a point, smallest first."""
    found = []
    for _, region in _geometry()._regions_for(map_id):
        for z in region["zones"]:
            if z["right"] <= y <= z["left"] and z["bottom"] <= x <= z["top"]:
                area = (z["left"] - z["right"]) * (z["top"] - z["bottom"])
                found.append((area, zone_display(z["name"])))
    return [name for _, name in sorted(found)]


def place_at(map_id, x, y) -> str:
    """A ground point as a reader would say it: "the Menethil Harbor docks
    (Wetlands)", "Menethil Harbor (Wetlands)", "Westfall", "The Deadmines"."""
    map_id = int(map_id)
    x, y = float(x), float(y)
    zone = zone_at(map_id, x, y)
    if map_kind(map_id) not in (CONTINENT, ""):
        return zone
    dock = _nearest(_doors() + DOCKS, map_id, x, y, DOCK_YARDS)
    if dock:
        return "%s (%s)" % (dock, zone)
    town = _nearest(_towns(), map_id, x, y, TOWN_YARDS)
    if not town:
        return zone
    name, town_zone = town
    # A city's flight master stands in the city: "Stormwind City", not
    # "Stormwind (Elwynn Forest)".
    if zone.startswith(name):
        return zone
    return "%s (%s)" % (name, zone_display(town_zone))


def parse_ground_aim(aim: str):
    """`at:<map>:<x>,<y>[,<z>]` as (map, x, y), or None."""
    text = str(aim or "").strip()
    if not text.startswith("at:"):
        return None
    head, _, rest = text[3:].partition(":")
    parts = rest.split(",")
    try:
        return int(head), float(parts[0]), float(parts[1])
    except (ValueError, IndexError):
        return None


def trigger_place(trigger_id) -> tuple[str, str]:
    """(how, place) for a teleporting doorway: ("out of", "Shadowfang Keep"),
    ("into", "The Deadmines") or ("through the portal to", "Darnassus").
    ("", "") for an id no teleport row holds."""
    try:
        row = triggers().get(int(trigger_id))
    except (TypeError, ValueError):
        row = None
    if not row:
        return "", ""
    here, there = int(row["map"]), int(row["to_map"])
    if is_instance(here) and not is_instance(there):
        return "out of", map_name(here)
    if is_instance(there):
        return "into", map_name(there)
    return "through the portal to", place_at(there, row["to_x"], row["to_y"])


def aim_place(aim: str) -> str:
    """Where a module aim points, named: a doorway by its instance, a ground
    point by its town and zone, `banker` as "the banker"."""
    text = str(aim or "").strip()
    if not text:
        return "nowhere"
    if text.startswith("trigger:"):
        how, place = trigger_place(text.split(":", 1)[1])
        if not place:
            return (
                "a doorway (trigger %s) the world database does not hold"
                % (text.split(":", 1)[1])
            )
        if how == "out of":
            return "the way out of " + place
        if how == "into":
            return "the door of " + place
        return "the portal to " + place
    ground = parse_ground_aim(text)
    if ground:
        return place_at(*ground)
    if text.startswith("at:"):
        return "a ground point the row does not spell whole (%s)" % text
    if text.isdigit():
        return "creature %s" % text
    return "the " + text


def walk_words(aim: str) -> str:
    """ "out of Shadowfang Keep", "into The Deadmines", "to Menethil Harbor
    (Wetlands)": the walk an aim asks for, after the verb."""
    text = str(aim or "").strip()
    if text.startswith("trigger:"):
        how, place = trigger_place(text.split(":", 1)[1])
        if place:
            return "%s %s" % (how, place)
    return "to " + aim_place(text)
