"""The lifelong goal: every recipe in the game, and who is first in line for it.

WHAT WAS ASKED FOR, in the operator's own words: "the family should get first dibs
on the rarest recipes, they should have a life long goal of getting all possible
recipes, and then there should be designated backup guild members who do other
stuff... there's specializations for professions and I want Grug to be armor
blacksmith, and you can choose who will be the other master professions, sort of
cascading order if there's extra recipes."

Three things, and this module is the second and third of them. guildcraft.py
already answers "what can the guild make and where does a missing recipe come
from"; what it could not answer is "how far along the whole road are we" and
"who is first in line when two people want the same trade". Both of those turn
on SPECIALIZATIONS, which nothing in this repository knew about before.

WHY A SPECIALIZATION IS THE HINGE. A profession is not one tree. At a certain
skill and a certain character level, a blacksmith walks to one NPC and becomes
an Armorsmith or a Weaponsmith, and the choice is EXCLUSIVE and permanent
without an unlearn: the grant spell carries SPELL_EFFECT_UNLEARN_SPECIALIZATION
(133) alongside its learn, and the quests share an ExclusiveGroup. So one
character can never reach 100% of a profession's recipes. Twelve Armorsmith
plate recipes and nine Weaponsmith weapon recipes are, for one blacksmith, an
either/or forever. The ONLY route to all of them is a SECOND blacksmith who
takes the other branch, which is exactly the "designated backup guild members"
half of the request, and it is why the hierarchy below is a list of SLOTS and
not a list of people.

EVERYTHING IN THE CATALOGUE BELOW WAS MEASURED, AND ONE PIECE OF RECEIVED
WISDOM WAS MEASURED WRONG
--------------------------------------------------------------------------
The brief this was built from stated, from memory, that Grumnus Steelshaper is
the WEAPONSMITH trainer in Ironforge and that Seril Scourgebane is the
Armorsmith in Blackrock Depths. Both halves are false on this realm, and four
independent columns say so. Measured live 2026-09-14 against the wow-dev world
database and against the DBCs inside the running worldserver's own image
(mod-playerbots/azerothcore-wotlk 47960183bb03b83e8943eb2f0f39c16df9710c9d):

  creature_template.subname  5164 Grumnus Steelshaper is "Armorsmith Trainer";
                             11146 Ironus Coldsteel is "Weaponsmith Trainer".
  quest_template             5283 "The Art of the Armorsmith" has Grumnus as
                             BOTH its creature_queststarter and its
                             creature_questender. 5284 "The Way of the
                             Weaponsmith" has Ironus as both.
  quest RewardSpell          5283 rewards 9790, 5284 rewards 9789.
  Spell.dbc                  9790 is named "Armorsmith" and 9789 "Weaponsmith",
                             both effect 36 (LEARN_SPELL) + 133
                             (UNLEARN_SPECIALIZATION). The spells they teach
                             are 9788 "Armorsmith" and 9787 "Weaponsmith", both
                             effect 47 (TRADE_SKILL).
  trainer_spell.ReqAbility1  Grumnus's list (TrainerId 124) gates its crafts on
                             9788; Ironus's (123) gates on 9787.

Five columns, no disagreement. Seril Scourgebane (11193) is not an Armorsmith
anything: he stands in Everlook on map 1 with Kilram and Lilith the Lithe, and
the three of them are the MASTER WEAPON sub-specialists - see UNREACHABLE.

THE OFFSET BETWEEN A GRANT AND ITS SPECIALIZATION IS NOT CONSTANT, which is the
trap that makes "read one pair and infer the rest" wrong. Blacksmithing's grant
is spec+2, leatherworking's is spec+1, Gnomish Engineering's is spec+1 while
Goblin's is spec-1, Spellfire's is spec-1 while Mooncloth's is spec+1. Every
pair below was read out of Spell.dbc by name and cross-checked against the
quest's own RewardSpell column; none was inferred from another.

THE NUMBERS ARE NOT RESTATED ANYWHERE ELSE. `craftbook.json` (generated by
tools/craftbook_from_dbc.py) is the only place a craft spell's NAME and opening
rank live, and `trainer_spell.ReqAbility1` in the world database is the only
place a craft's specialization gate lives. This module holds the CATALOGUE -
which specialization exists, what grants it, what it costs and where the NPC
stands - and nothing that either of those two already answers.

WHAT THIS MODULE CANNOT DO, AND SAYS SO RATHER THAN QUIETLY NOT DOING IT. See
STEERING_LIMIT. Thirty-five of the forty guild members cannot be sent anywhere
by this system, so every backup slot below is a RECRUITING TARGET and a piece
of documentation, never an errand. A hierarchy that silently assumed otherwise
would be the "reports success while doing nothing" failure professions.py's own
BLOCKERS constant exists to prevent.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Mapping, Sequence

import cast
import goals
import professions

CRAFTBOOK_FILE = "craftbook.json"


def load_craftbook(static_dir: str) -> dict:
    """The committed projection of every craft in the game, read once.

    THE SAME SHAPE THE OTHER THREE FROZEN BOOKS USE, and for the same reason
    armory.ItemBook and standing.StandingBook use it: the data is client DBC
    content that acore_world's own `skilllineability_dbc` does not carry (it is
    EMPTY on this realm, 0 rows, measured 2026-09-05), so a file is the only
    place it can come from.

    AN ABSENT FILE IS AN EMPTY BOOK AND NOT A CRASH. A worldserver image that
    predates this file, or a container built before it was added, must thin the
    Trades view rather than take the whole map server down - which is the guard
    the Trades endpoint already applies to a missing TABLE (infra#3172) applied
    to a missing FILE. An empty book produces no professions and the view says
    so, rather than a page of zeroes that reads like a family that knows
    nothing.
    """
    path = os.path.join(static_dir, CRAFTBOOK_FILE)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError):
        return {}


# Spell.dbc effect ids, named so the catalogue's provenance comments can be
# read without a lookup. A SPECIALIZATION spell is effect 47 with nothing after
# it; the base profession spells (9785 "Blacksmithing", 10662 "Leatherworking")
# are effect 47 followed by 118 and are NOT specializations, which is the one
# way a naive "effect 47" scan goes wrong.
SPELL_EFFECT_LEARN_SPELL = 36
SPELL_EFFECT_TRADE_SKILL = 47
SPELL_EFFECT_UNLEARN_SPECIALIZATION = 133

# What state one craft is in, for the character who would learn it. ROLE NAMES
# and never a colour: the page turns these into a chip tone, and the stylesheet
# is the only thing that knows the site is drawn on two grounds. The same rule
# guildcraft.NOW / SHORT / LEVEL_GATED already follow.
KNOWN = "known"
LEARNABLE = "learnable"
BLOCKED_SKILL = "skill"
BLOCKED_SPEC = "spec"
UNREACHABLE = "unreachable"

# The order the five states are reported in, hardest-won first. Printed rather
# than implied, because a bar chart in this order reads as progress and in any
# other order reads as noise.
STATE_ORDER = (KNOWN, LEARNABLE, BLOCKED_SKILL, BLOCKED_SPEC, UNREACHABLE)

# What each state is CALLED on the page, and which of the stylesheet's four
# tones it is drawn in. Written here rather than in JavaScript for the reason
# test_recap_tab.ThePageDecidesNothing established and this whole view is held
# to: a word a reader acts on is a judgement, and a judgement composed on the
# page is one no Python test can reach. `tone` is a ROLE the stylesheet knows
# and never a colour - the site is drawn on two grounds and the stylesheet is
# the only thing that knows it.
STATE_WORDS = {
    KNOWN: ("known", "up"),
    LEARNABLE: ("learnable now", "up"),
    BLOCKED_SKILL: ("behind more skill", ""),
    BLOCKED_SPEC: ("behind a branch nobody took", "no"),
    UNREACHABLE: ("no route on this realm", "no"),
}

# And what a SPECIALIZATION in each state is called, which is a different set of
# words for the same five states because they describe a different thing. "known"
# is right for a recipe and wrong for a branch: a branch is HELD, and one whose
# rival is held is not merely unknown, it is shut for that character forever.
SPEC_WORDS = {
    KNOWN: ("held", "up"),
    LEARNABLE: ("ready to take", "up"),
    BLOCKED_SKILL: ("not yet", ""),
    BLOCKED_SPEC: ("closed off for good", "no"),
    UNREACHABLE: ("no route on this realm", "no"),
}

# AcquireMethod, out of SkillLineAbility.dbc and carried through craftbook.json.
# 0 is an explicit grant - a trainer purchase, a quest, a recipe item - and it
# PERSISTS to `character_spell`. 1 is auto-learned on a rank-up and is NEVER
# written back, because Player::_SaveSpells skips an UNCHANGED spell.
#
# THIS DISTINCTION IS LOAD-BEARING AND IT COST THIS PROJECT A DAY ALREADY.
# professions.py records the measurement: 0 of 457 tailors hold 2963 Bolt of
# Linen Cloth in `character_spell` and Og was WATCHED CASTING IT. So for an
# AcquireMethod 1 craft the spellbook cannot answer the question at all, and a
# completion figure that counted its absence as "missing" would report the
# family at a fraction of its real total, forever, with nothing failing. Every
# such craft at or under the holder's skill is counted KNOWN here, and the
# basis says it is counted rather than observed.
#
# THERE ARE THREE VALUES AND ONLY ONE OF THEM IS "EXPLICIT", which a first pass
# at this got wrong by testing for 1 alone. AzerothCore's own names for them are
# 0 (trained), SKILL_LINE_ABILITY_LEARNED_ON_SKILL_LEARN = 1 and
# SKILL_LINE_ABILITY_LEARNED_ON_SKILL_VALUE = 2, and 1 and 2 are the same kind
# of thing: the core grants them, nothing buys them, and `_SaveSpells` skips
# them for the same reason. Counted over the committed projection: 3622 rows at
# 0, 79 at 1 and exactly ONE at 2 (spell 10846, the Artisan First Aid rank).
# One row is precisely the shape of thing a test written against today's data
# would never catch, so the test is written against the RULE - anything that is
# not 0 is automatic - rather than against the two values that happen to occur.
ACQUIRE_TRAINED = 0
ACQUIRE_AUTOMATIC = 1
ACQUIRE_AUTOMATIC_AT_RANK = 2


def is_automatic(acquire: int) -> bool:
    """Does the core grant this craft rather than somebody buying it?

    The one question `character_spell` cannot answer, so it is asked HERE and
    before the spellbook is consulted. See ACQUIRE_TRAINED above for why it is
    a rule and not a pair of literals.
    """
    return int(acquire) != ACQUIRE_TRAINED


@dataclass(frozen=True)
class Spec:
    """One specialization, as five columns of this realm agree it exists.

    `spell` is the specialization itself (Spell.dbc effect 47) and is what
    `trainer_spell.ReqAbility1` and `item_template.RequiredSpell` are gated on.
    `grant` is the spell the QUEST casts, which learns `spell` and unlearns any
    rival. They are different numbers with the same display name, and confusing
    them is why the catalogue carries both rather than one and an offset.

    `rival_group` is the quest ExclusiveGroup. Two specs sharing one are
    mutually exclusive for a single character, which is the whole reason the
    hierarchy below needs backup slots at all.
    """

    key: str
    label: str
    skill: int
    spell: int
    grant: int
    quest: int
    quest_title: str
    npc: int
    npc_name: str
    npc_map: int
    rival_group: int
    req_rank: int
    req_level: int
    # "" when the world has a working route to it. A sentence when it does not,
    # and the sentence is the evidence rather than a verdict - see UNREACHABLE.
    unreachable: str = ""


# EVERY SPECIALIZATION THIS REALM CARRIES, for the professions the family and
# the guild hold. Alliance rows only where a profession has two faction copies:
# all five of the family are Alliance (one Gnome, one Dwarf, three Humans,
# whatever the names suggest), which professions.py's BLOCKERS already records
# and `characters.race` confirms - 1, 1, 1, 3, 7.
#
# `npc_map` IS NOT DECORATION. mod-overseer's ResolveTravelTarget refuses a
# spawn on another map (mod_overseer.cpp:10044) because MoveFarTo paths through
# PathGenerator and there is no navmesh across an ocean. All five of the family
# stand on MAP 1 as of 2026-09-14, so a specialization whose only NPC is on map
# 0 or map 530 is a goal this system cannot walk anybody to TODAY. That is a
# fact about where they happen to be standing, not about the specialization, so
# it is reported live by `reach_line` and never baked into the choice.
#
# ENCHANTING HAS NO SPECIALIZATION AND ITS ABSENCE HERE IS A MEASUREMENT.
# Spell.dbc carries no effect-47 spell on skill line 333 beyond the four rank
# spells, and no quest in quest_template_addon gates on RequiredSkillID 333
# above rank 1. Og's second trade therefore has no branch to choose, which is
# why the hierarchy gives him one specialization and not two.
SPECS = (
    # ---- blacksmithing (164) ------------------------------------------------
    Spec(
        key="armorsmith",
        label="Armorsmith",
        skill=164,
        spell=9788,
        grant=9790,
        quest=5283,
        quest_title="The Art of the Armorsmith",
        npc=5164,
        npc_name="Grumnus Steelshaper",
        npc_map=0,
        rival_group=5283,
        req_rank=200,
        req_level=40,
    ),
    Spec(
        key="weaponsmith",
        label="Weaponsmith",
        skill=164,
        spell=9787,
        grant=9789,
        quest=5284,
        quest_title="The Way of the Weaponsmith",
        npc=11146,
        npc_name="Ironus Coldsteel",
        npc_map=0,
        rival_group=5283,
        req_rank=200,
        req_level=40,
    ),
    # THE THREE MASTER WEAPON SUB-SPECIALIZATIONS, AND WHY THEY ARE LISTED AT
    # ALL. They are listed because 24 blacksmithing crafts are gated on them
    # and a denominator that silently omitted those 24 would be reporting a
    # 100% that is not 100%. They are marked unreachable because this realm has
    # no route to them, which was measured three ways in one query alongside a
    # non-zero control so a broken query could not read as an absence:
    #   trainer_spell rows teaching 17039/17040/17041      0  (control: 3)
    #   quest_template RewardSpell or RewardDisplaySpell   0
    #   item_template spellid_1/2/3                        0
    # The quests exist - 5305, 5306, 5307, at Lilith the Lithe, Kilram and
    # Seril Scourgebane in Everlook on map 1, requiring blacksmithing 250 and
    # level 50 - and every one of them has RewardSpell 0, so completing one
    # grants nothing. Upstream teaches these at the same NPC after the quest;
    # this world database has no creature_default_trainer row for any of the
    # three. Filed as a finding, not routed around.
    Spec(
        key="swordsmith",
        label="Master Swordsmith",
        skill=164,
        spell=17039,
        grant=0,
        quest=5307,
        quest_title="Corruption",
        npc=11193,
        npc_name="Seril Scourgebane",
        npc_map=1,
        rival_group=0,
        req_rank=250,
        req_level=50,
        unreachable=(
            "quest 5307 Corruption exists at Seril Scourgebane and its "
            "RewardSpell is 0, and no trainer_spell row, quest reward or item "
            "in this world database teaches 17039 Master Swordsmith. The "
            "eight crafts behind it cannot be reached by anybody on this "
            "realm until a world-data fix lands"
        ),
    ),
    Spec(
        key="hammersmith",
        label="Master Hammersmith",
        skill=164,
        spell=17040,
        grant=0,
        quest=5305,
        quest_title="Sweet Serenity",
        npc=11191,
        npc_name="Lilith the Lithe",
        npc_map=1,
        rival_group=0,
        req_rank=250,
        req_level=50,
        unreachable=(
            "quest 5305 Sweet Serenity exists at Lilith the Lithe and its "
            "RewardSpell is 0, and nothing in this world database teaches "
            "17040 Master Hammersmith. Its eight crafts are out of everyone's "
            "reach"
        ),
    ),
    Spec(
        key="axesmith",
        label="Master Axesmith",
        skill=164,
        spell=17041,
        grant=0,
        quest=5306,
        quest_title="Snakestone of the Shadow Huntress",
        npc=11192,
        npc_name="Kilram",
        npc_map=1,
        rival_group=0,
        req_rank=250,
        req_level=50,
        unreachable=(
            "quest 5306 Snakestone of the Shadow Huntress exists at Kilram "
            "and its RewardSpell is 0, and nothing in this world database "
            "teaches 17041 Master Axesmith. Its eight crafts are out of "
            "everyone's reach"
        ),
    ),
    # ---- leatherworking (165) -----------------------------------------------
    Spec(
        key="dragonscale",
        label="Dragonscale Leatherworking",
        skill=165,
        spell=10656,
        grant=10657,
        quest=5141,
        quest_title="Dragonscale Leatherworking",
        npc=7866,
        npc_name="Peter Galen",
        npc_map=1,
        rival_group=5141,
        req_rank=225,
        req_level=40,
    ),
    Spec(
        key="elemental",
        label="Elemental Leatherworking",
        skill=165,
        spell=10658,
        grant=10659,
        quest=5144,
        quest_title="Elemental Leatherworking",
        npc=7868,
        npc_name="Sarah Tanner",
        npc_map=0,
        rival_group=5141,
        req_rank=225,
        req_level=40,
    ),
    Spec(
        key="tribal",
        label="Tribal Leatherworking",
        skill=165,
        spell=10660,
        grant=10661,
        quest=5143,
        quest_title="Tribal Leatherworking",
        npc=7870,
        npc_name="Caryssia Moonhunter",
        npc_map=1,
        rival_group=5141,
        req_rank=225,
        req_level=40,
    ),
    # ---- tailoring (197) ----------------------------------------------------
    Spec(
        key="spellfire",
        label="Spellfire Tailoring",
        skill=197,
        spell=26797,
        grant=26796,
        quest=10832,
        quest_title="Becoming a Spellfire Tailor",
        npc=22213,
        npc_name="Gidge Spellweaver",
        npc_map=530,
        rival_group=10831,
        req_rank=325,
        req_level=60,
    ),
    Spec(
        key="mooncloth",
        label="Mooncloth Tailoring",
        skill=197,
        spell=26798,
        grant=26799,
        quest=10831,
        quest_title="Becoming a Mooncloth Tailor",
        npc=22208,
        npc_name="Nasmara Moonsong",
        npc_map=530,
        rival_group=10831,
        req_rank=325,
        req_level=60,
    ),
    Spec(
        key="shadoweave",
        label="Shadoweave Tailoring",
        skill=197,
        spell=26801,
        grant=26800,
        quest=10833,
        quest_title="Becoming a Shadoweave Tailor",
        npc=22212,
        npc_name="Andrion Darkspinner",
        npc_map=530,
        rival_group=10831,
        req_rank=325,
        req_level=60,
    ),
    # ---- engineering (202) --------------------------------------------------
    Spec(
        key="goblin",
        label="Goblin Engineer",
        skill=202,
        spell=20222,
        grant=20221,
        quest=3639,
        quest_title="Show Your Work",
        npc=8126,
        npc_name="Nixx Sprocketspring",
        npc_map=1,
        rival_group=3526,
        req_rank=200,
        req_level=10,
    ),
    Spec(
        key="gnomish",
        label="Gnomish Engineer",
        skill=202,
        spell=20219,
        grant=20220,
        quest=3641,
        quest_title="Show Your Work",
        npc=7944,
        npc_name="Tinkmaster Overspark",
        npc_map=0,
        rival_group=3526,
        req_rank=200,
        req_level=10,
    ),
    # ---- alchemy (171) ------------------------------------------------------
    # ALL THREE GATE ZERO CRAFTS, AND THAT IS A MEASUREMENT RATHER THAN AN
    # OMISSION. No trainer_spell row carries ReqAbility1 28672, 28675 or 28677,
    # and no class-9 item_template row carries RequiredSpell of any of them.
    # They are a THROUGHPUT choice - a chance of extra output from a craft the
    # alchemist could already make - so they move nothing at all toward the
    # 100% recipe goal this page is about. Listed anyway, because "the alchemy
    # specialization is missing from the hierarchy" is a question somebody will
    # ask, and "it exists and grants no recipes" is the answer.
    Spec(
        key="elixir",
        label="Elixir Master",
        skill=171,
        spell=28677,
        grant=28678,
        quest=10902,
        quest_title="Master of Elixirs",
        npc=19052,
        npc_name="Lorokeem",
        npc_map=530,
        rival_group=10897,
        req_rank=325,
        req_level=68,
    ),
    Spec(
        key="potion",
        label="Potion Master",
        skill=171,
        spell=28675,
        grant=28676,
        quest=10897,
        quest_title="Master of Potions",
        npc=17909,
        npc_name="Lauranna Thar'well",
        npc_map=530,
        rival_group=10897,
        req_rank=325,
        req_level=68,
    ),
    Spec(
        key="transmute",
        label="Transmutation Master",
        skill=171,
        spell=28672,
        grant=28674,
        quest=10899,
        quest_title="Master of Transmutation",
        npc=22427,
        npc_name="Zarevhi",
        npc_map=530,
        rival_group=10897,
        req_rank=325,
        req_level=68,
    ),
)

BY_KEY = {spec.key: spec for spec in SPECS}
BY_SPELL = {spec.spell: spec for spec in SPECS}


@dataclass(frozen=True)
class Slot:
    """One place in the crafting hierarchy, and who is meant to stand in it.

    `holder` is a LIVE family name or "" for a slot nobody fills. An empty
    holder is the honest shape for a backup: see STEERING_LIMIT, nothing in
    this system can make a non-family guild member do anything, so a slot with
    a guild member's name written in it would be a claim rather than a plan.
    """

    spec_key: str
    holder: str
    why: str


# WHO THE FAMILY PUTS WHERE, AND WHY EACH ONE.
#
# THE ONE THAT WAS HANDED DOWN. Grug is the Armorsmith because the operator said
# so, in those words. Everything below it is a choice this module made, and
# each carries the measurement it was made on rather than a preference.
#
# THE RULE THE CHOICES WERE MADE BY, applied in this order:
#   1. Can the character WEAR what the specialization makes? professions.py
#      already encodes this as CRAFT_ARMOUR and checks it with `suits_wearer`:
#      a crafter who wears what they make is a crafter whose best work is worth
#      making. It is the first filter because it disqualifies outright.
#   2. Is the output itemized for what the character DOES? A leather set full
#      of Intellect is not a rogue's, whatever its armour class.
#   3. Only then, how many crafts does it unlock.
# Recipe count is LAST on purpose and it changed an answer: Dragonscale unlocks
# eight crafts against Elemental's five, and Bork takes Elemental anyway.
#
# The names are the LIVE five. `slots_for` puts this table through cast.rename
# for whichever world a process serves, exactly as professions.roster_for does.
_LIVE_FAMILY_SLOTS = (
    Slot(
        spec_key="armorsmith",
        holder="Grug",
        why=(
            "the operator's own instruction, and the character it already suited: "
            "Grug is the plate-wearing warrior who tanks, and professions.ROSTER "
            "pairs his blacksmithing with mining for exactly that reason. "
            "Armorsmith's twelve crafts are plate and mail armour, including the "
            "Breastplate of Kings and Bulwark of the Ancient Kings, which is the "
            "gear he takes hits in. The rival branch, Weaponsmith, makes weapons "
            "he would have to hand to somebody else"
        ),
    ),
    Slot(
        spec_key="elemental",
        holder="Bork",
        why=(
            "the only one of the three leatherworking branches whose best work "
            "Bork can both WEAR and WANT, which is what decided it against the "
            "branch with more recipes. Bork is a rogue, so he wears LEATHER "
            "(item_template subclass 2). Dragonscale's eight crafts are every one "
            "of them MAIL (subclass 3) - the Netherstrike and Ebon Netherscale "
            "sets - so he could never equip a single thing he made. Tribal's five "
            "are leather but the Windhawk set is Intellect and Spirit (stat types "
            "5 and 6), which is a caster druid's and worth nothing to a rogue. "
            "Elemental's five are leather AND agility: the Primalstrike set is "
            "epic, item level 115 to 120, and Primalstrike Vest carries Agility "
            "38, Stamina 39 and hit rating 12, which is rogue itemization exactly. "
            "Eight recipes he cannot use are worth less than five he can"
        ),
    ),
    Slot(
        spec_key="spellfire",
        holder="Og",
        why=(
            "Og is the mage, and Spellfire is the only one of the three tailoring "
            "branches itemized for one. All three make epic cloth robes at item "
            "level 105 to 120: Spellfire Robe is crit rating 28 and Intellect 17, "
            "Frozen Shadoweave Robe is Intellect 20 and Stamina 30, and Primal "
            "Mooncloth Robe is Intellect 20 and Spirit 20. Crit and Intellect is a "
            "damage caster's; Stamina is a warlock's survivability and Spirit is a "
            "healer's regeneration, and Og is neither. All three unlock three "
            "crafts, so nothing was given up on count"
        ),
    ),
    Slot(
        spec_key="goblin",
        holder="Grog",
        why=(
            "a genuine tie on everything that usually decides, broken on the one "
            "thing that is measurable today. Gnomish and Goblin unlock NINETEEN "
            "crafts each, and Grog is a paladin, so neither makes armour he wears "
            "- rules 1 and 2 above are silent and rule 3 is a draw. What is not a "
            "draw is where the two trainers stand: Nixx Sprocketspring is on MAP 1 "
            "in Gadgetzan, which is the continent all five of the family are "
            "standing on, and Tinkmaster Overspark is on map 0 in Ironforge, which "
            "ResolveTravelTarget refuses outright because there is no navmesh "
            "across an ocean. One of the two is a walk and the other is not "
            "reachable at all, and they unlock the same number of recipes"
        ),
    ),
    Slot(
        spec_key="elixir",
        holder="Ugga",
        why=(
            "chosen last and worth the least, and that is stated rather than "
            "dressed up: no alchemy specialization gates a single craft on this "
            "realm, so this slot moves the 100% goal by exactly zero recipes. "
            "Measured - nothing in trainer_spell carries ReqAbility1 28672, 28675 "
            "or 28677 and no recipe item requires one. What the three do is add "
            "output to a craft the alchemist could already make, so the choice is "
            "about what the family DRINKS rather than what it can learn. Ugga is "
            "the priest and the healer, and an elixir or a flask is the thing a "
            "healer hands out before a fight rather than during one"
        ),
    ),
)


def slots_for(which: str | None = None) -> tuple:
    """The family's slot table as `which` world spells it. Live is identity.

    The REASONS are renamed too, for the same reason professions.roster_for
    renames them: each one names other characters, and a dev plan justified by
    the names of characters in the other world is a plan nobody can check.
    """
    return tuple(
        Slot(
            spec_key=slot.spec_key,
            holder=cast.rename(slot.holder, which),
            why=cast.retext(slot.why, which),
        )
        for slot in _LIVE_FAMILY_SLOTS
    )


FAMILY_SLOTS = slots_for()

# THE BACKUP SLOTS. Every specialization the family has locked itself out of by
# taking its rival, plus the raw professions nobody in the family holds at all.
#
# THESE ARE NOT PEOPLE AND MUST NEVER BECOME PEOPLE WITHOUT A MECHANISM. See
# STEERING_LIMIT. `holder=""` is the whole honesty of this table: a slot is a
# RECRUITING TARGET, which a human can act on by inviting an unguilded
# character of the right profession, and it is documentation for anybody asking
# why the guild's completion figure is stuck below 100%.
#
# WHY THEY ARE ORDERED THE WAY `hierarchy` ORDERS THEM rather than typed in an
# order here: the rule is "how many crafts does this slot unlock that NOTHING
# ELSE in the hierarchy can reach", counted live against the world's own
# trainer_spell gating, and a typed order would be that count written down
# twice and allowed to drift. `_order_line` prints the rule above the list.
_BACKUP_KEYS = (
    "weaponsmith",
    "gnomish",
    "dragonscale",
    "tribal",
    "mooncloth",
    "shadoweave",
    "potion",
    "transmute",
    "swordsmith",
    "hammersmith",
    "axesmith",
)

# THE HARD LIMIT, AND IT IS STATED AT THE TOP OF EVERY VIEW THIS MODULE FEEDS.
#
# Only the characters in `overseer_roster` are ever sent a command by this
# system. The guild has forty members and five of them are the family; the
# other thirty-five run their own AI and cannot be told to walk to a trainer,
# take a specialization, craft a thing or hold a profession. There is no verb
# for it and adding one is not a Python change.
#
# SO A BACKUP SLOT IS TWO THINGS AND NEITHER OF THEM IS AN ERRAND: it is a
# recruiting target a person can fill by hand, and it is the reason a number on
# this page is not 100%. Anything more would be a mechanism that reports
# success while doing nothing, which is the failure this repository has the
# most scar tissue about.
STEERING_LIMIT = (
    "ONLY THE FIVE IN overseer_roster CAN BE TOLD TO DO ANYTHING. The other "
    "guild members play their own AI: nothing in this system can send one to a "
    "trainer, make one take a specialization, or ask one to craft. So every "
    "backup slot below is a RECRUITING TARGET for a person to fill by hand and "
    "a reason this page is not at 100%, and it is never an errand. A slot with "
    "a name in it would be a claim that something is being worked on when "
    "nothing is."
)

# WHY THE FAMILY'S OWN CHOICES ARE ALSO NOT ERRANDS YET, which is a different
# refusal from the one above and has to stay separate from it. The family CAN
# be steered; what they cannot yet be steered to do is hand in a quest at a
# named NPC in order to take a specialization. mod-overseer's TrainOnArrival
# buys a SKILL from a trainer (professions.py documents the whole road), and a
# specialization is not bought, it is a quest turn-in. Whether the existing
# quest-drive verbs cover an NPC quest hand-in is a question about C++ that
# this module cannot answer and must not assume.
GRANT_REFUSAL = (
    "Taking a specialization is a QUEST TURN-IN at a named NPC, not a trainer "
    "purchase, so mod-overseer's TrainOnArrival does not cover it: that verb "
    "buys a skill through Trainer::TeachSpell. Whether the quest drive can be "
    "aimed at one of these NPCs and made to hand in is a C++ question, and a "
    "C++ change needs a worldserver promotion that restarts the realm. Until "
    "somebody answers it, every specialization below is a goal this page "
    "TRACKS and not one it can take."
)


def _skill_word(skill: int) -> str:
    """The word for a skill id, out of the one table that has them."""
    for word, number in goals.SKILL_IDS.items():
        if number == int(skill):
            return word
    return "skill %d" % int(skill)


def specs_for_skill(skill: int) -> tuple:
    """Every specialization on one profession, in catalogue order."""
    return tuple(spec for spec in SPECS if spec.skill == int(skill))


def rivals_of(spec: Spec) -> tuple:
    """The specializations this one locks a single character out of.

    Keyed on the quest ExclusiveGroup, which is what the world actually
    enforces, rather than on "same profession": the three Master weapon
    sub-specs sit on blacksmithing beside Armorsmith and Weaponsmith and are
    NOT rivals of either - a Weaponsmith goes on to take one of them. Their
    rival_group is 0 and a 0 matches nothing, which is the honest answer and
    not an accident.
    """
    if not spec.rival_group:
        return ()
    return tuple(
        other
        for other in SPECS
        if other.rival_group == spec.rival_group and other.key != spec.key
    )


def chosen_spec(holder: str, slots: Sequence | None = None) -> Spec | None:
    """The specialization this character is meant to end up with, or None."""
    for slot in FAMILY_SLOTS if slots is None else slots:
        if slot.holder == holder:
            return BY_KEY[slot.spec_key]
    return None


def held_specs(spells: Sequence) -> tuple:
    """Which specializations a character's spellbook says they already hold.

    READ OFF THE SPECIALIZATION SPELL AND NOT THE GRANT. The grant is cast once
    by the quest and `character_spell` is not where it lands; the effect-47
    spell is the one the world keeps and the one every trainer row is gated on.

    Trustworthy in both directions here, and that is worth saying because it is
    NOT true of craft spells. professions.py's rule is to read
    SkillLineAbility.AcquireMethod before trusting `character_spell`, and every
    specialization spell is an explicit grant, so a row means held and no row
    means not held.
    """
    have = {int(spell) for spell in spells}
    return tuple(spec for spec in SPECS if spec.spell in have)


def spec_state(spec: Spec, value: int, level: int, held: Sequence) -> str:
    """Where one character stands on one specialization.

    Five answers and they must not collapse. A specialization already held is
    not the same as one a rival has closed off, and neither is the same as one
    the world has no route to for anybody - the last is a defect in the world
    data and the other two are progress.
    """
    if spec in held:
        return KNOWN
    if spec.unreachable:
        return UNREACHABLE
    if any(rival in held for rival in rivals_of(spec)):
        return BLOCKED_SPEC
    if int(level) < spec.req_level or int(value) < spec.req_rank:
        return BLOCKED_SKILL
    return LEARNABLE


def spec_line(
    spec: Spec, value: int, level: int, held: Sequence, holder: str, on_map: int
) -> str:
    """What stands between this character and this specialization, in one line.

    EVERY GATE IS NAMED SEPARATELY BECAUSE THEY FAIL DIFFERENTLY. Skill is
    ground out by crafting; a character level is ground out by playing; a
    continent is a refusal no amount of either clears; and a rival
    specialization is a door that has already shut. A sentence that said only
    "not yet" would flatten four different problems into one shrug.
    """
    state = spec_state(spec, value, level, held)
    word = _skill_word(spec.skill)
    if state == KNOWN:
        return "%s holds %s already" % (holder, spec.label)
    if state == UNREACHABLE:
        return "%s: %s" % (spec.label, spec.unreachable)
    if state == BLOCKED_SPEC:
        shut = ", ".join(rival.label for rival in rivals_of(spec) if rival in held)
        return (
            "%s can never take %s now: %s is exclusive with it and is "
            "already held" % (holder, spec.label, shut)
        )
    gates = []
    if int(value) < spec.req_rank:
        gates.append(
            "%s %d, and %s has %d, which is %d short"
            % (word, spec.req_rank, holder, int(value), spec.req_rank - int(value))
        )
    if int(level) < spec.req_level:
        gates.append(
            "character level %d, and %s is %d" % (spec.req_level, holder, int(level))
        )
    where = reach_line(spec, on_map, holder)
    if not gates:
        opening = (
            "%s meets everything quest %d %s asks for, and %s is who "
            "hands it over" % (holder, spec.quest, spec.quest_title, spec.npc_name)
        )
        return opening + (". " + where if where else "")
    return "quest %d %s asks for %s. %s is who hands it over%s" % (
        spec.quest,
        spec.quest_title,
        ", and ".join(gates),
        spec.npc_name,
        ". " + where if where else "",
    )


def reach_line(spec: Spec, on_map: int, holder: str) -> str:
    """Whether the NPC is on the continent this character is standing on.

    "" when it is, because a walk that is possible needs no sentence. A
    sentence when it is not, and it is a live measurement rather than a
    property of the specialization: professions.py's BLOCKERS records that this
    claim was quietly false for long enough to mislead an investigation, and
    the fix was to re-measure `characters.map` rather than to write it down.
    """
    if not on_map or int(on_map) == int(spec.npc_map):
        return ""
    return (
        "%s stands on map %d and %s is on map %d, which "
        "ResolveTravelTarget refuses outright: there is no navmesh across "
        "an ocean, so this is not a long walk, it is a refusal"
        % (spec.npc_name, spec.npc_map, holder, int(on_map))
    )


# ----------------------------------------------------------- the 100% figure --
#
# THE DENOMINATOR IS THE WHOLE PROBLEM, and it is why craftbook.json exists.
# `item_template` class 9 holds only the recipes that exist as an ITEM - a
# pattern off a vendor, a plan off a corpse - which is a minority of any
# profession: blacksmithing has 118 of them against 525 abilities on its skill
# line. A completion figure built on the item table would have read 100% while
# four hundred crafts were still unlearned, which is the exact class of
# false-green this repository keeps finding.
#
# So the denominator is every ability on the skill line, out of
# SkillLineAbility.dbc, and the numerator is counted against it.


def effective_rank(entry: Sequence, world_rank) -> int:
    """The skill a craft actually asks for, from the best source available.

    THE DBC FIELD NAMED "ReqSkillValue" IS NOT IT, and reading it as the gate
    is how a first pass at this concluded that Og, at tailoring 50, could learn
    421 of the 439 tailoring crafts in the game. Measured over craftbook.json:
    that field is 1 for 439 of 439 tailoring abilities, 508 of 525
    blacksmithing and 258 of 264 alchemy. It is not a rank, it is a floor
    nearly everything sits on.

    THE REAL GATE IS IN THE WORLD DATABASE, and it arrives here as
    `world_rank`: the lowest of `trainer_spell.ReqSkillRank` for every trainer
    that teaches it and `item_template.RequiredSkillRank` for the recipe item
    that carries it. The LOWEST, because those are alternative routes in and a
    craft is gated by the cheapest one, not by the dearest.

    THE FALLBACK IS THE YELLOW VALUE, for the handful of crafts the world
    database places nowhere - no trainer sells them and no item teaches them.
    `TrivialSkillLineRankLow` is the skill at which a craft stops granting a
    guaranteed point, so it is always at or above the true learn rank. Falling
    back to it can only UNDER-report what is learnable, and under-reporting is
    the only safe direction here: this number's whole job is to say when the
    family has reached 100%, and a gate set too low would let it say so early.
    """
    if world_rank is not None:
        return int(world_rank)
    return max(int(entry[1]), int(entry[2]))


def _craft_state(
    rank: int,
    acquire: int,
    gate: int,
    value: int,
    known_spells: frozenset,
    spell: int,
    held: Sequence,
) -> str:
    """Which of the five states one craft is in for one holder.

    THE ACQUIRE METHOD IS CHECKED BEFORE THE SPELLBOOK AND THE ORDER MATTERS.
    An AcquireMethod 1 craft is never written to `character_spell` at all, so
    asking the spellbook about one gets "no" forever however many times the
    character has cast it. professions.py measured this: 0 of 457 tailors hold
    2963 Bolt of Linen Cloth, and Og was watched casting it. A craft like that
    at or under the holder's skill is counted KNOWN, and the basis says counted
    rather than observed so nobody reads it as an observation.
    """
    if spell in known_spells:
        return KNOWN
    if gate:
        spec = BY_SPELL.get(gate)
        if spec is not None:
            if spec.unreachable:
                return UNREACHABLE
            if spec not in held:
                # A craft behind a specialization this character has not taken.
                # BLOCKED_SPEC whether the door is merely shut-for-now or shut
                # forever, because from the family's side both are "somebody
                # else has to take this branch", which is what a backup slot
                # is. The hierarchy is where the difference is spelled out.
                return BLOCKED_SPEC
    if is_automatic(acquire) and int(value) >= int(rank):
        return KNOWN
    if int(value) >= int(rank):
        return LEARNABLE
    return BLOCKED_SKILL


def _percent(known: int, total: int) -> int:
    """Whole percent, rounded DOWN, and never 100 unless it really is.

    Rounded down on purpose: 99.6% of a profession reported as 100% is the one
    number on this page a reader would act on and be wrong about, and the whole
    feature is a goal somebody is trying to finish.
    """
    if not total:
        return 0
    return min(100, (known * 100) // total)


def profession_completion(
    skill: int,
    crafts: Mapping,
    holders: Sequence,
    gates: Mapping,
    ranks: Mapping,
    known_by: Mapping,
    slots: Sequence | None = None,
) -> dict:
    """How far one profession is along the road to every recipe in it.

    `crafts` is craftbook.json's entry for this skill line: spell id -> [name,
    reqSkillValue, trivialLow, acquireMethod, createdItem]. `ranks` is spell id
    -> the skill the world actually asks for, and `gates` is spell id ->
    specialization spell; both come from the world database, where the trainer
    rows and the recipe items are the only two places either fact lives.

    THE BEST HOLDER IS WHO IT IS COUNTED AGAINST, singular, and that is a
    deliberate narrowing rather than a shortcut. "The guild knows this recipe"
    is a different question from "the guild's blacksmith knows this recipe",
    and only the second one is a road anybody is walking: a recipe known by a
    character who will never take blacksmithing again is not progress toward
    the family's blacksmith knowing it. With no holder at all every craft is
    BLOCKED_SKILL, which is the honest reading of a profession nobody has.
    """
    best = holders[0]["who"] if holders else ""
    value = int(holders[0]["value"]) if holders else 0
    known_spells = frozenset(known_by.get(best, ()))
    held = held_specs(known_spells)
    counts = {state: 0 for state in STATE_ORDER}
    for spell, entry in crafts.items():
        spell = int(spell)
        state = _craft_state(
            effective_rank(entry, ranks.get(spell)),
            int(entry[3]),
            int(gates.get(spell, 0)),
            value,
            known_spells,
            spell,
            held,
        )
        counts[state] += 1
    total = sum(counts.values())
    return {
        "skill": int(skill),
        "name": _skill_word(skill),
        "holder": best,
        "counts": counts,
        "total": total,
        "known": counts[KNOWN],
        "percent": _percent(counts[KNOWN], total),
        "line": _completion_line(_skill_word(skill), best, counts, total),
        "chips": _count_chips(counts),
    }


def _count_chips(counts: Mapping) -> list:
    """One chip per state that is not zero, in STATE_ORDER.

    A ZERO IS NOT DRAWN, and that is the whole reason this is a function rather
    than five fixed chips. "0 behind a branch nobody took" beside a profession
    with no branches at all is a chip that makes a reader look for something
    that is not there, and five of them on every row would bury the two that
    matter.
    """
    out = []
    for state in STATE_ORDER:
        if not counts.get(state):
            continue
        word, tone = STATE_WORDS[state]
        out.append({"text": "%d %s" % (counts[state], word), "tone": tone})
    return out


def _completion_line(word: str, holder: str, counts: Mapping, total: int) -> str:
    """One profession's standing, counted rather than judged.

    Every state that is non-zero is named. A sentence that reported only the
    percentage would hide WHICH wall the rest is behind, and the four walls
    need different answers: skill is crafting, a specialization is a second
    crafter, and unreachable is a world-data fix nobody here can make.
    """
    if not holder:
        return (
            "nobody holds %s, so all %d of its crafts are behind somebody "
            "taking the trade" % (word, total)
        )
    said = [
        "%s knows %d of the %d crafts on the %s skill line, which is %d%%"
        % (holder, counts[KNOWN], total, word, _percent(counts[KNOWN], total))
    ]
    if counts[LEARNABLE]:
        said.append(
            "%d more are under the skill already ground and are a "
            "trainer visit or a recipe away" % counts[LEARNABLE]
        )
    if counts[BLOCKED_SKILL]:
        said.append("%d sit above that skill" % counts[BLOCKED_SKILL])
    if counts[BLOCKED_SPEC]:
        said.append(
            "%d are behind a specialization this character has not "
            "taken, which needs a second crafter rather than more "
            "grinding" % counts[BLOCKED_SPEC]
        )
    if counts[UNREACHABLE]:
        said.append(
            "%d cannot be reached by anybody on this realm" % counts[UNREACHABLE]
        )
    return (
        ", and ".join(said)
        if len(said) == 1
        else (said[0] + ". " + "; ".join(said[1:]))
    )


def overall_line(professions_done: Sequence) -> str:
    """The one number the operator asked for, and what it is a fraction of."""
    total = sum(row["total"] for row in professions_done)
    known = sum(row["known"] for row in professions_done)
    if not total:
        return (
            "nothing here could read a craft list, so there is no "
            "completion figure to give"
        )
    return (
        "%d of %d crafts known across %d professions, which is %d%% of "
        "every recipe in the game for the trades this guild touches"
        % (known, total, len(professions_done), _percent(known, total))
    )


# -------------------------------------------------------------- the ladder --


def _slot_row(spec: Spec, holder: str, why: str, unlocks: int, exclusive: int) -> dict:
    """One rung, with what it is worth and who is on it."""
    return {
        "spec": spec.key,
        "label": spec.label,
        "skill": spec.skill,
        "profession": _skill_word(spec.skill),
        "holder": holder,
        "why": why,
        "unlocks": unlocks,
        "exclusive": exclusive,
        "family": bool(holder),
        "reachable": not spec.unreachable,
        "line": _slot_line(spec, holder, unlocks, exclusive),
        "chips": _rung_chips(spec, holder, unlocks),
    }


def _rung_chips(spec: Spec, holder: str, unlocks: int) -> list:
    """What a collapsed rung has to carry: whose it is, and what it is worth.

    THE FIRST CHIP IS THE ONE THAT MATTERS and it says which of three kinds of
    rung this is, because the ladder mixes all three and they call for
    completely different responses: a family rung is being walked toward, an
    empty one needs a person to recruit somebody, and an unreachable one needs
    a world-data fix nobody on this page can make.
    """
    if spec.unreachable:
        chips = [{"text": "no route on this realm", "tone": "no"}]
    elif holder:
        chips = [{"text": holder, "tone": "up"}]
    else:
        chips = [{"text": "nobody in this slot", "tone": "unsure"}]
    chips.append({"text": _skill_word(spec.skill), "tone": ""})
    chips.append(
        {
            "text": ("%d crafts" % unlocks) if unlocks != 1 else "1 craft",
            "tone": "" if unlocks else "unsure",
        }
    )
    return chips


def _slot_line(spec: Spec, holder: str, unlocks: int, exclusive: int) -> str:
    """What this rung is, said in the terms it matters in.

    A FAMILY RUNG AND A BACKUP RUNG ARE DIFFERENT SENTENCES because they are
    different KINDS of thing: one is a goal somebody is walking toward and the
    other is a hole in the roster. Writing both as "Armorsmith: 12 recipes"
    would let a reader take the second for the first, which is the whole
    mistake STEERING_LIMIT exists to stop.

    A RUNG WORTH NOTHING SAYS SO IN WORDS RATHER THAN PRINTING A ZERO. All
    three alchemy specializations gate no craft at all on this realm, and "0
    crafts" beside a rung reads like a page that failed to count rather than
    like a branch that genuinely adds no recipe. The distinction matters
    because the two call for opposite responses: one is a bug to fix and the
    other is a slot nobody should spend a recruit on.
    """
    what = ("%d crafts" % unlocks) if unlocks != 1 else "1 craft"
    if spec.unreachable:
        return "%s: %s are gated on it and nobody on this realm can take it. %s" % (
            spec.label,
            what,
            spec.unreachable,
        )
    if holder and not unlocks:
        return (
            "%s takes %s for the family, and it unlocks no recipe at all: "
            "this branch adds output to crafts they could already make, so "
            "it moves the completion figure by nothing and was chosen on "
            "what the family drinks rather than on what it can learn"
            % (holder, spec.label)
        )
    if holder:
        return "%s takes %s for the family, first in line for the %s behind it" % (
            holder,
            spec.label,
            what,
        )
    if not unlocks:
        return (
            "%s is an empty BACKUP SLOT that is not worth filling: it "
            "gates no craft on this realm, so recruiting for it would add "
            "nothing to the %d%% figure above" % (spec.label, 0)
        )
    return (
        "%s is a BACKUP SLOT with nobody in it: %s are behind it, and no "
        "member of the family can ever take it because the family's own %s "
        "has taken an exclusive rival branch. Only a recruited %s who "
        "chooses this branch can reach them"
        % (spec.label, what, _skill_word(spec.skill), _skill_word(spec.skill))
    )


def _order_line() -> str:
    """The rule the ladder is in, printed above it rather than implied.

    guildcraft._order's rule, and for the same reason: a list in an order is
    read as a finding whether or not anybody meant it to be.
    """
    return (
        "The family first, because they get first dibs: one rung each, in the "
        "order of how many crafts that specialization unlocks. Then the backup "
        "slots nobody fills, in the same order, so the biggest hole in the "
        "guild's recipe coverage is at the top. Then the specializations this "
        "realm has no route to at all, last, because no recruiting fills those. "
        "The count beside each rung is crafts gated on that specialization in "
        "trainer_spell and in the recipe items, counted live and not typed in."
    )


def hierarchy(gates: Mapping, slots: Sequence | None = None) -> list:
    """The cascading order, family first and backups after, worth-first within.

    `gates` is craft spell -> specialization spell, from the world's own
    `trainer_spell.ReqAbility1`. The COUNT beside each rung is derived from it
    rather than typed, so a rung cannot claim a worth the world disagrees with.
    """
    slots = FAMILY_SLOTS if slots is None else slots
    unlocks: dict = {}
    for gate in gates.values():
        unlocks[int(gate)] = unlocks.get(int(gate), 0) + 1

    by_holder = {slot.spec_key: slot for slot in slots}
    family = [
        _slot_row(
            BY_KEY[slot.spec_key],
            slot.holder,
            slot.why,
            unlocks.get(BY_KEY[slot.spec_key].spell, 0),
            unlocks.get(BY_KEY[slot.spec_key].spell, 0),
        )
        for slot in slots
    ]
    family.sort(key=lambda row: (-row["unlocks"], row["label"]))

    backups = []
    unreachable = []
    for key in _BACKUP_KEYS:
        spec = BY_KEY[key]
        if key in by_holder:
            continue
        row = _slot_row(
            spec, "", "", unlocks.get(spec.spell, 0), unlocks.get(spec.spell, 0)
        )
        (unreachable if spec.unreachable else backups).append(row)
    backups.sort(key=lambda row: (-row["unlocks"], row["label"]))
    unreachable.sort(key=lambda row: (-row["unlocks"], row["label"]))

    ladder = family + backups + unreachable
    for place, row in enumerate(ladder, start=1):
        row["rank"] = place
    return ladder


def coverage_gaps(holders_by_skill: Mapping) -> list:
    """The professions with nobody on them at all, which is the other kind of gap.

    A SPECIALIZATION GAP AND A PROFESSION GAP ARE NOT THE SAME HOLE. The first
    is "the family took the other branch"; the second is "nobody in this guild
    has this trade", and only the second can be answered by a family member
    changing their mind. professions.UNASSIGNED already names the two the
    family left open ON PURPOSE for a guild to cover, so those are reported as
    a decision rather than as a defect - the same distinction guildcraft's
    `_gap_line` makes, read from the same constant so the two cannot drift.
    """
    out = []
    for word in sorted(professions.CRAFTING):
        skill = goals.SKILL_IDS.get(word)
        if skill is None or holders_by_skill.get(skill):
            continue
        deliberate = word in professions.UNASSIGNED
        out.append(
            {
                "name": word,
                "skill": skill,
                "deliberate": deliberate,
                "line": (
                    "%s: nobody holds it, and the family's own trade table leaves "
                    "it open on purpose for the guild to cover, so it is a "
                    "decision waiting on members rather than a mistake" % word
                    if deliberate
                    else "%s: nobody in the guild holds it, so every craft on its skill "
                    "line is behind somebody taking the trade" % word
                ),
            }
        )
    return out


def craft_facts(craft_rows: Sequence) -> tuple:
    """(rank by spell, specialization gate by spell) out of the world's rows.

    `craft_rows` are the UNION of two reads that answer the same two questions
    about a craft from different tables: `trainer_spell` (what a trainer sells,
    at what rank, behind which specialization) and class-9 `item_template`
    (what a recipe item teaches, at what rank, behind which specialization).

    BOTH TABLES ARE NEEDED AND READING ONLY THE FIRST WAS A MEASURED MISTAKE.
    The three tailoring specializations gate NO trainer row at all - their
    crafts are recipe ITEMS carrying `RequiredSpell` - so a gate map built from
    `trainer_spell` alone reported Spellfire, Mooncloth and Shadoweave as
    unlocking zero crafts each, which is three false zeroes on the one page
    that exists to count. Weaponsmith was under-counted the same way, at 6
    instead of 9.

    THE LOWEST RANK WINS, because the rows are alternative routes to the same
    craft and the cheapest is the one that gates it. A craft sold by a trainer
    at 260 and carried by a world-drop pattern at 250 asks for 250.
    """
    ranks: dict = {}
    gates: dict = {}
    for row in craft_rows:
        spell = int(row.get("SpellId") or 0)
        if not spell:
            continue
        rank = row.get("ReqSkillRank")
        if rank is not None:
            rank = int(rank)
            if spell not in ranks or rank < ranks[spell]:
                ranks[spell] = rank
        gate = int(row.get("ReqAbility1") or 0)
        # Only a gate this catalogue recognises. `ReqAbility1` also carries
        # ordinary prerequisite spells - a rank-2 enchant requiring its rank-1 -
        # and reading one of those as a specialization would report a craft as
        # blocked behind a branch that does not exist.
        if gate in BY_SPELL:
            gates[spell] = gate
    return ranks, gates


def build_tradespec(
    craftbook: Mapping,
    craft_rows: Sequence,
    skill_rows: Sequence,
    spell_rows: Sequence,
    member_rows: Sequence,
    roster: Sequence,
    slots: Sequence | None = None,
) -> dict:
    """The whole view: the 100% figure, the ladder, and what stops both.

    `craftbook` is the committed projection of SkillLineAbility.dbc joined to
    Spell.dbc - every craft in the game per profession - and it is the
    DENOMINATOR. `craft_rows` are the world's own rows about those crafts: what
    rank each asks for and which specialization gates it. See `craft_facts`.

    EVERY ARGUMENT IS AN OBSERVATION HANDED IN, and nothing here goes and gets
    one. Same seam as professions.plan and guildcraft.build_guildcraft, and the
    same guarantee: this module has no path to the world, so it cannot invent a
    reading of it.
    """
    wanted = set(roster)
    levels = {row["name"]: int(row.get("level") or 0) for row in member_rows}
    maps = {row["name"]: int(row.get("map") or 0) for row in member_rows}
    known_by: dict = {}
    for row in spell_rows:
        if row["name"] in wanted:
            known_by.setdefault(row["name"], set()).add(int(row["spell"]))

    holders_by_skill: dict = {}
    for row in skill_rows:
        if row["name"] not in wanted:
            continue
        holders_by_skill.setdefault(int(row["skill"]), []).append(
            {
                "who": row["name"],
                "value": int(row.get("value") or 0),
                "max": int(row.get("max") or 0),
                "level": levels.get(row["name"], 0),
            }
        )
    for found in holders_by_skill.values():
        found.sort(key=lambda h: (-h["value"], -h["max"], h["who"]))

    ranks, gates = craft_facts(craft_rows)

    done = []
    for skill in sorted(int(key) for key in craftbook):
        crafts = craftbook[str(skill)]
        if not crafts:
            continue
        done.append(
            profession_completion(
                skill,
                crafts,
                holders_by_skill.get(skill, []),
                gates,
                ranks,
                known_by,
                slots,
            )
        )
    done.sort(key=lambda row: (-row["percent"], row["name"]))

    ladder = hierarchy(gates, slots)
    specs = _spec_cards(holders_by_skill, known_by, maps, slots)
    return {
        "line": overall_line(done),
        "percent": _percent(
            sum(row["known"] for row in done), sum(row["total"] for row in done)
        ),
        "professions": done,
        "specs": specs,
        "hierarchy": ladder,
        "order": _order_line(),
        "gaps": coverage_gaps(holders_by_skill),
        "limit_line": STEERING_LIMIT,
        "grant_line": GRANT_REFUSAL,
        # AN EMPTY BOOK AND A FAMILY THAT KNOWS NOTHING LOOK IDENTICAL FROM THE
        # PAGE, and only this sentence can keep them apart. craftbook.json is a
        # committed file, so it is absent exactly when a container was built
        # without it - and a row of 0% across fourteen professions is a claim
        # somebody would act on.
        "empty_note": (
            "craftbook.json could not be read, so there is no list "
            "of crafts to measure against and every figure here "
            "would be zero. That is a missing file in this "
            "container and not a guild that knows nothing."
            if not done
            else ""
        ),
        "basis": _basis(bool(gates)),
    }


def _spec_cards(
    holders_by_skill: Mapping,
    known_by: Mapping,
    maps: Mapping,
    slots: Sequence | None = None,
) -> list:
    """Each family member's own specialization, and what stands in the way."""
    out = []
    for slot in FAMILY_SLOTS if slots is None else slots:
        spec = BY_KEY[slot.spec_key]
        holders = holders_by_skill.get(spec.skill, [])
        mine = next((h for h in holders if h["who"] == slot.holder), None)
        value = mine["value"] if mine else 0
        level = mine["level"] if mine else 0
        held = held_specs(known_by.get(slot.holder, ()))
        state = spec_state(spec, value, level, held)
        word, tone = SPEC_WORDS[state]
        out.append(
            {
                "spec": spec.key,
                "label": spec.label,
                "holder": slot.holder,
                "profession": _skill_word(spec.skill),
                "skill": spec.skill,
                "quest": spec.quest,
                "quest_title": spec.quest_title,
                "npc": spec.npc_name,
                "state": state,
                "why": slot.why,
                "line": spec_line(
                    spec, value, level, held, slot.holder, maps.get(slot.holder, 0)
                ),
                "chips": [
                    {"text": word, "tone": tone},
                    {"text": _skill_word(spec.skill), "tone": ""},
                ],
            }
        )
    return out


def _basis(gated: bool) -> str:
    """What this view read, and the several things it is not saying.

    The house rule guildcraft._basis follows: the weakest claim goes first,
    because a reader who takes a counted number for an observed one will act on
    it.
    """
    gate_note = (
        "Which crafts sit behind a specialization is trainer_spell.ReqAbility1 "
        "in this realm's own world database, read live."
        if gated
        else "trainer_spell returned no ReqAbility1 rows this time, so NO craft is "
        "reported as specialization-gated. That is a missing read and not a "
        "profession without branches: the counts beside the hierarchy rungs "
        "will all be zero and should not be believed."
    )
    return (
        "THE COUNT OF WHAT IS KNOWN IS PART OBSERVED AND PART COUNTED, and the "
        "difference is not decoration. A craft whose SkillLineAbility "
        "AcquireMethod is 0 is an explicit grant and PERSISTS to "
        "character_spell, so a row there means known and no row means not "
        "known. A craft whose AcquireMethod is 1 is auto-learned on a rank-up "
        "and is NEVER written back, because Player::_SaveSpells skips an "
        "unchanged spell: measured on this realm, 0 of 457 tailors hold 2963 "
        "Bolt of Linen Cloth and one of the family was watched casting it. So "
        "an AcquireMethod 1 craft at or under the holder's skill is COUNTED as "
        "known here rather than observed, and the true figure could be lower "
        "if the world refuses one for a reason this page cannot see. "
        + gate_note
        + " The denominator is every ability on the profession's "
        "skill line out of SkillLineAbility.dbc, committed as craftbook.json "
        "by tools/craftbook_from_dbc.py and regenerated from the DBCs inside "
        "the running worldserver's own image. It is deliberately NOT "
        "item_template class 9, which holds only the recipes that exist as an "
        "ITEM: blacksmithing has 118 of those against 525 abilities, so a "
        "figure built on the item table would have read 100% with four hundred "
        "crafts unlearned. Completion is counted against ONE holder per "
        "profession, the one with the highest ground skill, because a recipe "
        "known by somebody who will never take the trade again is not progress "
        "toward the family's crafter knowing it. Percentages are rounded DOWN, "
        "so 100% means 100%."
    )
