"""Which recipe a character should stand and cast, to level a crafting trade.

WHY THIS SUITE EXISTS (infra#440). craft.py answers exactly one question -
given a character who already holds a crafting skill at some value, which
recipe (if any) is worth aiming them at right now - and nothing else. The
mod_overseer.cpp side (DriveCraft) is what actually casts the spell and reads
the reagents back from the character's real bags; this module never touches
either, which is what these tests hold it to.
"""

import pathlib
import unittest

import craft
import goals
import professions
import travel

# ---------------------------------------------------------------------------
# THE WORLDSERVER'S OWN ANSWER FOR EVERY SPELL `craft.RECIPES` NAMES.
# `Spell.dbc` field 18, `RequiresSpellFocus`, resolved through
# `SpellFocusObject.dbc`: 0 none, 1 Anvil, 2 Loom, 3 Forge, 4 Cooking Fire.
#
# WHY THIS TABLE EXISTS AT ALL (infra#3760, built as part of infra#3748). The
# guard this replaces was `assertEqual(recipe.focus, 0)`, and `Recipe.focus`
# DEFAULTS to 0 - so it compared the declared field against itself and could
# never fail. Eleven Engineering entries declared 0 while the server required
# an Anvil, every one of them refused on every twenty-second poll for its whole
# life, in a table that had a test for exactly this. infra#3758 worked around
# it by pinning focus-4 spell ids by number and infra#3747 did the same for the
# smelts; both catch one focus id each and neither catches a wrong value for
# any spell nobody happened to list. This is the projection infra#3760 asked
# for instead: every id the table names, against the server's answer, so a new
# entry cannot be added without stating a measurement in a second place.
#
# PROVENANCE, AND IT IS CHECKABLE RATHER THAN ASSERTED. Read on 2026-09-13 from
# `/azerothcore/env/dist/data/dbc/` copied out of the running worldserver pod
# and md5-verified byte-identical against the pod's own `md5sum`:
#
#     Spell.dbc             543b9fe61355b6a77a01714d52fea2e5   49839 x 234
#     SkillLineAbility.dbc  d8c11abfcfe70596cb9068c0e97a1d9a   10219 x 14
#     SpellFocusObject.dbc  797c65a49ae1e6336c9d851eb18011e0
#
# `tools/spell_focus_from_dbc.py` regenerates this block from those files, so
# the next reader re-derives it in one command rather than by hand.
#
# THE FIELD INDEX IS THE TRAP, AND THE ANCHOR DOES NOT CATCH IT. infra#3689's
# anchor - spell 2963 resolves to Reagent[0]=2589, ReagentCount[0]=2 - proves
# Reagent/ReagentCount/EffectItemType/SpellName and touches neither focus nor
# tool. `RequiresSpellFocus` is field **18** and `EquippedItemClass` field
# **68** in the 3.3.5a layout. Read at 23 and 69 - which a first pass at this
# did, and which infra#3747's own write-up implies - every smelt answers
# `focus = 0` and only eleven spells in the whole file carry any value at all.
# The tell is the total: the real field is non-zero for 647 Anvil spells alone.
MEASURED_FOCUS = {
    # TAILORING
    2963: 0,
    8776: 0,
    2964: 0,
    3839: 0,
    3865: 0,
    18401: 0,
    # FIRST AID
    3275: 0,
    # ENGINEERING - eleven Anvils, and infra#3760 is the issue for them
    3918: 0,
    3922: 1,
    7430: 1,
    3923: 1,
    3929: 0,
    3931: 0,
    3973: 0,
    3938: 1,
    3945: 0,
    12585: 0,
    12590: 1,
    12589: 1,
    12591: 1,
    12599: 1,
    12619: 1,
    19788: 0,
    19791: 1,
    19795: 1,
    # MINING - the one focus-gated entry that has a walk (infra#3748)
    2657: 3,
    # ALCHEMY - 3450 and 11467 are the raid-consumable brackets, and their
    # focus is a measurement rather than an inherited assumption: the brief
    # that asked for them stated that Alchemy's high-tier flasks need an
    # "Alchemy Lab" focus, and on this realm that is FALSE for every flask,
    # elixir and potion. Alchemy Lab is focus 663 and exactly six spells in
    # the whole file want it, all of them Alchemist's Stones.
    2330: 0,
    2337: 0,
    3447: 0,
    3450: 0,
    3173: 0,
    7181: 0,
    11449: 0,
    11450: 0,
    11457: 0,
    11460: 0,
    11467: 0,
    17553: 0,
    17556: 0,
    # BLACKSMITHING - 2665 is gone, see craft.py's COLOUR BANDS block, and
    # 9920 Solid Grinding Stone is gone too, replaced at the same bracket by
    # 9918 Solid Sharpening Stone - see craft.py's RAID CONSUMABLES block
    2660: 0,
    3320: 0,
    3326: 0,
    3337: 0,
    9918: 0,
    16641: 0,
    # LEATHERWORKING
    2881: 0,
    2152: 0,
    9058: 0,
    3756: 0,
    3763: 0,
    2167: 0,
    7135: 0,
    20649: 0,
    3818: 0,
    3780: 0,
    7151: 0,
    7156: 0,
    10487: 0,
    10507: 0,
    10548: 0,
    10558: 0,
    19049: 0,
    19082: 0,
}

# THE SIBLING PROJECTION, FOR THE TWO FIELDS NOTHING CHECKED AT ALL.
# spell id -> (MinSkillLineRank, TrivialSkillLineRankLow, TrivialSkillLineRankHigh)
# straight out of the running worldserver's `SkillLineAbility.dbc`
# (d8c11abfcfe70596cb9068c0e97a1d9a), regenerated by
# tools/spell_bands_from_dbc.py. Checked in for the same reason MEASURED_FOCUS
# is: CI runs this suite stdlib-only with no cluster access, so a checked-in
# projection is the only form of the server's answer a pull request can be
# gated on, and being a second copy is the point - one of the two has to be
# typed from memory and the other cannot be.
#
# `min_skill` and `max_skill` were guide numbers until this table existed, and
# TEN of the sixty-one entries disagreed with the realm. See craft.py's COLOUR
# BANDS block for the list and for why a wrong edge is invisible from outside.
MEASURED_BANDS = {
    # TAILORING
    2963: (1, 25, 50),
    8776: (1, 50, 85),
    2964: (1, 90, 105),
    3839: (1, 135, 145),
    3865: (1, 180, 185),
    18401: (1, 255, 260),
    # FIRST AID
    3275: (1, 30, 60),
    # ENGINEERING
    3918: (1, 20, 40),
    3922: (1, 45, 60),
    7430: (1, 70, 90),
    3923: (1, 60, 90),
    3929: (1, 85, 95),
    3931: (1, 90, 105),
    3973: (1, 110, 140),
    3938: (1, 105, 155),
    3945: (1, 125, 145),
    12585: (1, 175, 195),
    12590: (1, 175, 215),
    12589: (1, 195, 235),
    12591: (1, 200, 240),
    12599: (1, 215, 255),
    12619: (1, 235, 275),
    19788: (1, 250, 260),
    19791: (1, 280, 300),
    19795: (1, 295, 315),
    # MINING
    2657: (1, 25, 70),
    # ALCHEMY - 2337's floor of 80 is the twenty-point wall Ugga walked into
    2330: (1, 55, 95),
    2337: (80, 85, 125),
    3447: (1, 135, 175),
    3450: (1, 195, 235),
    3173: (1, 145, 185),
    7181: (1, 175, 215),
    11449: (1, 205, 245),
    11450: (1, 215, 255),
    11457: (1, 230, 270),
    11460: (1, 245, 285),
    11467: (1, 255, 295),
    17553: (1, 275, 315),
    17556: (1, 290, 330),
    # BLACKSMITHING
    2660: (1, 15, 55),
    3320: (1, 45, 85),
    3326: (1, 75, 100),
    3337: (1, 125, 150),
    9918: (1, 200, 210),
    16641: (1, 255, 260),
    # LEATHERWORKING
    2881: (1, 20, 40),
    2152: (1, 30, 60),
    9058: (1, 40, 70),
    3756: (1, 85, 115),
    3763: (1, 110, 140),
    2167: (100, 125, 150),
    7135: (1, 140, 165),
    20649: (1, 150, 160),
    3818: (1, 160, 170),
    3780: (1, 170, 190),
    7151: (1, 195, 215),
    7156: (1, 210, 230),
    10487: (1, 220, 240),
    10507: (1, 225, 245),
    10548: (1, 250, 270),
    10558: (1, 255, 275),
    19049: (1, 280, 300),
    19082: (1, 310, 330),
}

# The eleven entries that declare a focus nothing in this repo walks to yet.
# NOT an excuse list: the test below asserts this is EXACTLY the set, so a
# twelfth cannot be added, and each of these is already filed (infra#3760 for
# the table, infra#3617 for the anvil walk). They are Engineering's whole
# ladder above Rough Blasting Powder.
FOCUS_WITHOUT_A_WALK = {
    3922,
    7430,
    3923,
    3938,
    12590,
    12589,
    12591,
    12599,
    12619,
    19791,
    19795,
}


class RecipeForTests(unittest.TestCase):
    def test_returns_none_in_the_gap_between_two_bolt_brackets(self):
        # 101-124 is a still-deliberate gap: Silk Headband and the rest of
        # the guide's later thread/dye Tailoring recipes are deferred past
        # infra#3609's own minimum ask (Linen Belt, added directly below).
        # recipe_for must not fall back to the Silk bolt just because it is
        # close by.
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["tailoring"], 101))
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["tailoring"], 124))

    def test_finds_linen_belt_bracket(self):
        # infra#3609's own acceptance criteria: the first Tailoring bracket
        # unblocked once craft_supply.REAGENTS could buy its thread.
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 61)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 8776)
        self.assertEqual(
            craft.recipe_for(goals.SKILL_IDS["tailoring"], 67).spell_id, 8776
        )

    def test_woolen_cloth_bracket_starts_after_linen_belt(self):
        # Woolen Cloth's own min_skill shifted from the guide's 61 to 68 to
        # make room for Linen Belt (61-67) directly below it.
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 68)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2964)

    def test_returns_none_above_every_bracket(self):
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["tailoring"], 301))

    def test_finds_bolt_of_woolen_cloth_bracket(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 75)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2964)

    def test_finds_bolt_of_silk_cloth_bracket(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 130)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3839)

    def test_finds_bolt_of_mageweave_bracket(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 180)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3865)

    def test_finds_bolt_of_runecloth_bracket(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 255)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 18401)

    def test_returns_none_for_a_profession_with_no_entry(self):
        # Enchanting is assigned in professions.py's own ROSTER (Og) but has
        # no verified recipe in craft.RECIPES - it is not even a plain
        # SPELL_EFFECT_CREATE_ITEM output (see the module docstring on why an
        # unverified/wrong-shaped id is never guessed in rather than left
        # absent).
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["enchanting"], 1))

    def test_finds_the_bracket_a_skill_value_falls_in(self):
        # 2963, NOT 3910. Spell 3910 is named "Tailoring" in the
        # worldserver's own Spell.dbc - the Expert rank profession spell,
        # no reagents, creates nothing - so this bracket named a non-recipe
        # for its whole life and DriveCraft dropped every errand built from
        # it (infra#3689). 2963 is the real Bolt of Linen Cloth, confirmed
        # by six live casts once the id was corrected.
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 1)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2963)

    def test_no_tailoring_bracket_names_a_profession_rank_spell(self):
        # The exact shape of infra#3689: 3908/3909/3910/3911/12180/26790 are
        # the Apprentice/Journeyman/Expert/Artisan/Master/Grand Master
        # Tailoring RANK spells, not recipes. One of them sat in this table
        # labelled "Bolt of Linen Cloth" because nothing asserted the
        # difference, and a rank spell creates no item, so the bracket could
        # never have worked for anyone.
        rank_spells = {3908, 3909, 3910, 3911, 12180, 26790}
        for recipe in craft.RECIPES[goals.SKILL_IDS["tailoring"]]:
            self.assertNotIn(recipe.spell_id, rank_spells)

    def test_bracket_boundaries_are_inclusive(self):
        self.assertIsNotNone(craft.recipe_for(goals.SKILL_IDS["tailoring"], 60))
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["tailoring"], 0))

    def test_blacksmithing_finds_the_bracket_a_skill_value_falls_in(self):
        # Grug's real starting bracket - Rough Sharpening Stone, 1-29.
        recipe = craft.recipe_for(goals.SKILL_IDS["blacksmithing"], 1)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2660)

    def test_blacksmithing_returns_none_in_an_anvil_gated_gap(self):
        # 91-124 is real skill range with real recipes (Runed Copper Belt,
        # Silver Rod, Rough Bronze Leggings) - all require an Anvil +
        # Blacksmith Hammer DriveCraft's v1 cannot satisfy, so this must stay
        # None rather than falling back to a stone recipe that would not
        # actually grant a skill-up there.
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["blacksmithing"], 100))

    def test_blacksmithing_finds_the_top_bracket(self):
        # Dense Sharpening Stone, 250-259 - the highest verified entry. It
        # ends at 259 and not 260 because 260 is its own grey value, where
        # the core rolls no skill-up at all.
        recipe = craft.recipe_for(goals.SKILL_IDS["blacksmithing"], 259)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 16641)

    def test_blacksmithing_stops_at_dense_sharpening_stones_grey(self):
        """260 IS THE GREY VALUE, not a bracket the table gave up on. Casting
        there produces the item and never the point - see craft.py's COLOUR
        BANDS block for the other nine edges that had the same fault."""
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["blacksmithing"], 260))

    def test_blacksmithing_returns_none_past_the_last_verified_bracket(self):
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["blacksmithing"], 261))

    def test_blacksmithing_never_aims_below_a_recipes_learn_floor(self):
        """THE 65-74 WALL THAT STOPPED GRUG. Coarse Sharpening Stone's
        MinSkillLineRank on this realm is 75, but the guide's route hands it
        the 65-75 band and the table copied that - so at 65 Grug was handed a
        spell he cannot hold and DriveCraft dropped it as a planner bug. Rough
        Grinding Stone (grey 85) covers the window instead."""
        blacksmithing = goals.SKILL_IDS["blacksmithing"]
        for value in range(65, 75):
            with self.subTest(skill_value=value):
                recipe = craft.recipe_for(blacksmithing, value)
                self.assertIsNotNone(recipe)
                self.assertEqual(recipe.spell_id, 3320)
        self.assertEqual(craft.recipe_for(blacksmithing, 75).spell_id, 3326)

    def test_coarse_sharpening_stone_is_gone_entirely(self):
        """Its honest bracket would be 75-79 (floor 75, grey 80), a window
        Coarse Grinding Stone already owns with a grey of 100. Pinned so it
        cannot come back from a guide reading."""
        for recipe in craft.RECIPES[goals.SKILL_IDS["blacksmithing"]]:
            self.assertNotEqual(recipe.spell_id, 2665)

    def test_leatherworking_picks_light_leather_at_skill_1(self):
        # 3x Ruined Leather Scraps -> 1x Light Leather, spell 2881, no
        # purchased reagent - the recycle recipe every leatherworker knows.
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 1)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2881)

    def test_leatherworking_picks_light_armor_kit_mid_bracket(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 30)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2152)

    def test_leatherworking_picks_heavy_leather_at_150(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 150)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 20649)

    def test_leatherworking_1_to_300_is_covered_with_no_gap_at_all(self):
        """THE LAST GAP IS CLOSED. 46-55 was the only hole left in this
        profession and it was held open by a misreading rather than a missing
        fact - see craft.py's comment beside the bracket. Every point of
        1-300 now answers."""
        for skill_value in range(1, 301):
            with self.subTest(skill_value=skill_value):
                self.assertIsNotNone(
                    craft.recipe_for(goals.SKILL_IDS["leatherworking"], skill_value)
                )

    def test_the_handstitched_leather_cloak_bracket_is_filled(self):
        """9058 was refused because no `trainer_spell` row teaches it and no
        pattern item names it. Both true; neither is evidence. Its
        SkillLineAbility row is AcquireMethod 1 / ClassMask 0 - auto-learned
        by every class - and an auto-learned ability has no trainer row BY
        DEFINITION, exactly as Smelt Copper and Linen Bandage already do in
        this same table."""
        leatherworking = goals.SKILL_IDS["leatherworking"]
        for value in range(46, 56):
            with self.subTest(skill_value=value):
                self.assertEqual(craft.recipe_for(leatherworking, value).spell_id, 9058)
        # and it hands off to Embossed Leather Gloves, which is ORANGE from 56
        self.assertEqual(craft.recipe_for(leatherworking, 56).spell_id, 3756)

    def test_leatherworking_picks_embossed_leather_gloves(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 100)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3756)

    def test_leatherworking_picks_fine_leather_belt(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 125)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3763)

    def test_leatherworking_picks_dark_leather_boots(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 126)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 2167)

    def test_leatherworking_picks_dark_leather_pants(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 149)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 7135)

    def test_leatherworking_picks_cured_heavy_hide(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 156)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3818)

    def test_leatherworking_picks_heavy_armor_kit(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 180)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3780)

    def test_leatherworking_picks_barbaric_shoulders(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 181)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 7151)

    def test_leatherworking_picks_guardian_gloves(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 200)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 7156)

    def test_leatherworking_picks_thick_armor_kit(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 205)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 10487)

    def test_leatherworking_picks_nightscape_headband(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 235)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 10507)

    def test_leatherworking_picks_nightscape_pants(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 250)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 10548)

    def test_leatherworking_picks_nightscape_boots(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 260)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 10558)

    def test_leatherworking_picks_wicked_leather_gauntlets(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 290)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 19049)

    def test_leatherworking_picks_runic_leather_headband_at_the_top(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["leatherworking"], 300)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 19082)


class EngineeringRecipeForTests(unittest.TestCase):
    """Engineering (infra#440's follow-up) is the first skill with more than
    one bracket, so it is what actually exercises `recipe_for` picking among
    several entries rather than the trivial single-entry case Tailoring
    covers above."""

    def test_first_bracket_covers_skill_one(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 1)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3918)  # Rough Blasting Powder

    def test_a_middle_bracket_answers_its_own_value(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 200)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 12589)  # Mithril Tube

    def test_last_bracket_covers_skill_three_hundred(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 300)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 19795)  # Thorium Tube

    def test_bronze_tube_now_fills_the_106_124_bracket(self):
        # infra#3616: Weak Flux is a real, verified vendor purchase (see
        # craft_supply.REAGENT), so Bronze Tube (spell 3938) now fills the
        # bracket that used to answer None here.
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 115)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3938)

    def test_standard_scope_is_still_deliberately_deferred(self):
        # Standard Scope's own reagent, Moss Agate, was checked against
        # acore_world.npc_vendor directly and found NOT vendor-sold (a mined
        # gem, not a general good) - so unlike Bronze Tube it stays out of
        # RECIPES, and skill 125 still answers with Heavy Blasting Powder's
        # own bracket rather than a Standard Scope entry that could never
        # complete. See craft.py's module-level comment.
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 125)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3945)  # Heavy Blasting Powder

    def test_the_explosive_sheep_chain_gap_answers_none(self):
        # 151-174: Whirring Bronze Gizmo / Bronze Framework / Explosive Sheep
        # collide with Heavy Blasting Powder's own skill window and cannot
        # all be stocked by this module's one-recipe-per-bracket model - see
        # craft.py's module-level comment.
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["engineering"], 160))


class ToolRecipeTests(unittest.TestCase):
    """The tool-vs-consumable distinction (infra#440's Engineering follow-up):
    a recipe that creates a permanent tool, not something to spam, is marked
    `repeatable=False` and MUST use a single-skill-point bracket - that
    narrow bracket, not an inventory check this module cannot make, is what
    stops DriveCraft from recasting it once the skill-up lands."""

    def test_every_non_repeatable_recipe_has_a_single_point_bracket(self):
        for recipes in craft.RECIPES.values():
            for recipe in recipes:
                if not recipe.repeatable:
                    self.assertEqual(
                        recipe.min_skill,
                        recipe.max_skill,
                        f"{recipe.name} is marked repeatable=False but spans "
                        f"more than one skill point - it would be recast "
                        f"like a consumable",
                    )

    def test_arclight_spanner_is_marked_not_repeatable(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 51)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 7430)
        self.assertFalse(recipe.repeatable)

    def test_gyromatic_micro_adjustor_is_marked_not_repeatable(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["engineering"], 195)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 12590)
        self.assertFalse(recipe.repeatable)

    def test_ordinary_consumable_recipes_default_to_repeatable(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["tailoring"], 1)
        self.assertTrue(recipe.repeatable)


class AlchemyRecipeForTests(unittest.TestCase):
    """One assertion per bracket - the full skill 1-300 Alchemy progression,
    verified against real spell/reagent data (see craft.RECIPES's own
    comment). Boundaries checked explicitly since the brackets abut without
    overlapping (RecipeTableDisciplineTests.test_brackets_do_not_overlap
    already holds the general shape; this pins the actual numbers)."""

    def test_minor_healing_potion_covers_1_to_79(self):
        """1-79, NOT the 1-59 an earlier pass wrote. Lesser Healing Potion's
        MinSkillLineRank on this realm is 80, so 60-79 used to name a recipe
        Ugga cannot hold - a twenty-point wall twenty-six points above where
        she stands. 2330's own grey is 95, so 79 is still conservative."""
        alchemy = goals.SKILL_IDS["alchemy"]
        for value in (1, 59, 60, 79):
            with self.subTest(skill_value=value):
                self.assertEqual(craft.recipe_for(alchemy, value).spell_id, 2330)

    def test_lesser_healing_potion_covers_80_to_109(self):
        # THE POTION-AS-REAGENT BRACKET: this recipe's own reagent is the
        # previous recipe's output (1x Minor Healing Potion), not a raw herb.
        # 80 is its MinSkillLineRank, read from the realm's own DBC.
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 80).spell_id, 2337)
        self.assertEqual(craft.recipe_for(alchemy, 109).spell_id, 2337)

    def test_healing_potion_covers_110_to_139(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 110).spell_id, 3447)
        self.assertEqual(craft.recipe_for(alchemy, 139).spell_id, 3447)

    def test_lesser_mana_potion_covers_140_to_154(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 140).spell_id, 3173)
        self.assertEqual(craft.recipe_for(alchemy, 154).spell_id, 3173)

    def test_greater_healing_potion_covers_155_to_174(self):
        """WAS 155-184. The last ten points went to Elixir of Fortitude, which
        is ORANGE across all of them (yellow 195) where this is YELLOW from
        175 - so the raid consumable is better on skill AND on output. See
        craft.py's RAID CONSUMABLES block."""
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 155).spell_id, 7181)
        self.assertEqual(craft.recipe_for(alchemy, 174).spell_id, 7181)

    def test_elixir_of_fortitude_covers_175_to_184(self):
        """The first raid consumable this family will ever reach, and the only
        one on this realm a TRAINER teaches below Alchemy 200."""
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 175).spell_id, 3450)
        self.assertEqual(craft.recipe_for(alchemy, 184).spell_id, 3450)

    def test_elixir_of_agility_covers_185_to_209(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 185).spell_id, 11449)
        self.assertEqual(craft.recipe_for(alchemy, 209).spell_id, 11449)

    def test_elixir_of_greater_defense_covers_210_to_214(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 210).spell_id, 11450)
        self.assertEqual(craft.recipe_for(alchemy, 214).spell_id, 11450)

    def test_superior_healing_potion_covers_215_to_229(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 215).spell_id, 11457)
        self.assertEqual(craft.recipe_for(alchemy, 229).spell_id, 11457)

    def test_elixir_of_detect_undead_covers_230_to_239(self):
        """WAS 230-264. Elixir of Greater Agility took the last twenty-five,
        being orange across all of them (yellow 255) where this goes yellow at
        245 - and it makes something a melee raider drinks rather than an
        elixir that detects undead."""
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 230).spell_id, 11460)
        self.assertEqual(craft.recipe_for(alchemy, 239).spell_id, 11460)

    def test_elixir_of_greater_agility_covers_240_to_264(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 240).spell_id, 11467)
        self.assertEqual(craft.recipe_for(alchemy, 264).spell_id, 11467)

    def test_superior_mana_potion_covers_265_to_274(self):
        """WAS 265-284. Major Healing Potion reaches down to 275, which is the
        rank this realm's own trainer_spell states for it - the top bracket was
        already a raid consumable and was simply starting ten points late."""
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 265).spell_id, 17553)
        self.assertEqual(craft.recipe_for(alchemy, 274).spell_id, 17553)

    def test_major_healing_potion_covers_275_to_300(self):
        alchemy = goals.SKILL_IDS["alchemy"]
        self.assertEqual(craft.recipe_for(alchemy, 275).spell_id, 17556)
        self.assertEqual(craft.recipe_for(alchemy, 300).spell_id, 17556)

    def test_nothing_above_300(self):
        self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["alchemy"], 301))


class CraftErrandTests(unittest.TestCase):
    def test_zero_for_a_character_with_no_crafting_trade(self):
        # Og holds tailoring + enchanting (professions.ROSTER). Tailoring at
        # 0 means "not learned yet" (professions.py's trainer errand owns
        # that), and enchanting still has no craft.RECIPES entry (a
        # non-CREATE_ITEM output, flagged deferred in the design doc) - so
        # this must fall all the way through to 0, never a guessed spell id.
        # No secondary (First Aid/Cooking) keys are given, so the fallback
        # below this loop also finds nothing learned.
        self.assertEqual(craft.craft_errand("Og", {"tailoring": 0, "enchanting": 1}), 0)

    def test_zero_for_a_trade_not_yet_learned(self):
        # Og is assigned tailoring but a skill value of 0 means the trainer
        # errand has not landed yet - craft.py must never invent a recipe for
        # a trade nobody has learned. professions.assigned("Og") includes
        # "tailoring" per the family's real assignment table.
        self.assertEqual(craft.craft_errand("Og", {"tailoring": 0}), 0)

    def test_finds_the_recipe_for_a_learned_crafting_trade(self):
        # Og: tailoring + enchanting. tailoring has a verified recipe;
        # enchanting does not (it is also a non-CREATE_ITEM output, flagged as
        # deferred in the design doc), so the learned tailoring value must be
        # what answers this.
        spell_id = craft.craft_errand("Og", {"tailoring": 1, "enchanting": 1})
        self.assertEqual(spell_id, 2963)

    def test_finds_the_alchemy_recipe_for_uggas_learned_trade(self):
        # Ugga: herbalism + alchemy (professions.ROSTER) - herbalism is a
        # GATHERING trade with no craft.RECIPES entry (it climbs on its own
        # per the module docstring), so the learned alchemy value must be
        # what answers this.
        spell_id = craft.craft_errand("Ugga", {"herbalism": 132, "alchemy": 80})
        self.assertEqual(spell_id, 2337)  # Lesser Healing Potion's bracket
        # and at 60 - where this test used to sit - she stays on the recipe
        # she can actually hold, because 2337's learn floor is 80.
        self.assertEqual(
            craft.craft_errand("Ugga", {"herbalism": 132, "alchemy": 60}), 2330
        )

    def test_finds_the_leatherworking_recipe_for_bork(self):
        # Bork: skinning + leatherworking (professions.ROSTER). Skinning is a
        # GATHERING trade with no craft.RECIPES entry, so the leatherworking
        # value is what must answer this.
        spell_id = craft.craft_errand("Bork", {"skinning": 40, "leatherworking": 1})
        self.assertEqual(spell_id, 2881)

    def test_never_answers_for_a_trade_this_character_does_not_hold(self):
        # Grug is assigned mining + blacksmithing (a GATHERING trade and a
        # CRAFTING one that now has verified recipe entries). Even if
        # `skills` claimed a tailoring value (bad data from a stale row,
        # say), craft_errand must not answer with a tailoring recipe for a
        # character professions.py never assigned it - the same permission
        # discipline professions.py itself holds for `wanted`.
        spell_id = craft.craft_errand("Grug", {"mining": 8, "tailoring": 50})
        self.assertEqual(spell_id, 0)

    def test_finds_grogs_engineering_recipe(self):
        # Grog: mining + engineering (professions.ROSTER). mining is a
        # GATHERING trade with no craft.RECIPES entry; engineering now has a
        # full bracket table, so his engineering value must be what answers
        # this.
        spell_id = craft.craft_errand("Grog", {"mining": 40, "engineering": 1})
        self.assertEqual(spell_id, 3918)  # Rough Blasting Powder

    def test_finds_the_recipe_for_grugs_blacksmithing(self):
        # Grug: mining + blacksmithing. mining is a GATHERING trade with no
        # RECIPES entry (it climbs on its own, per the module docstring);
        # blacksmithing now has Rough Sharpening Stone at 1-29.
        spell_id = craft.craft_errand("Grug", {"mining": 8, "blacksmithing": 1})
        self.assertEqual(spell_id, 2660)


class FirstAidAndCookingTests(unittest.TestCase):
    """infra#2757's Cooking/First Aid slice - the two SECONDARY skills every
    family character already holds, verified independently of the
    per-character CRAFTING assignment `professions.assigned` gates."""

    def test_finds_linen_bandage_bracket(self):
        recipe = craft.recipe_for(goals.SKILL_IDS["first aid"], 1)
        self.assertIsNotNone(recipe)
        self.assertEqual(recipe.spell_id, 3275)

    def test_linen_bandage_runs_to_its_real_grey_value(self):
        """59, not 39 (infra#3614).

        `SkillLineAbility.dbc` from the running worldserver gives 3275 a grey
        (TrivialSkillLineRankHigh) of 60, so 59 is the last value it can still
        grant a point at. The old 39 was not a measurement of 3275 at all - it
        was where Heavy Linen Bandage used to take over, and that recipe is a
        trainer purchase this family cannot reach.
        """
        first_aid = goals.SKILL_IDS["first aid"]
        for value in (1, 39, 40, 59):
            with self.subTest(value=value):
                recipe = craft.recipe_for(first_aid, value)
                self.assertIsNotNone(recipe)
                self.assertEqual(recipe.spell_id, 3275)

    def test_nothing_past_linen_bandages_grey(self):
        # 60 is 3275's grey value: it stops granting skill-ups there, and no
        # other First Aid recipe is reachable without a Journeyman trainer
        # (infra#3614, mod-overseer#454). Better no errand than a cast that
        # consumes cloth for nothing.
        for value in (60, 74, 75):
            with self.subTest(value=value):
                self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["first aid"], value))

    def test_no_heavy_linen_bandage_bracket_at_any_value(self):
        """3276 is a trainer purchase for every class this family has.

        Its auto-learn SkillLineAbility row is ClassMask 0x20 - Death Knight
        and nothing else. The all-class row (ClassMask 0x5DF) is
        AcquireMethod 0, i.e. `trainer_spell` at ReqSkillRank 40 for 100
        copper, and the nearest Alliance-usable First Aid trainer is 15,513
        yards across an ocean `ResolveTravelTarget` refuses (infra#3732).
        Naming it here produces a `craft_spell` DriveCraft drops as a planner
        bug, which is how First Aid came to stall silently at 39.
        """
        first_aid = goals.SKILL_IDS["first aid"]
        named = {r.spell_id for r in craft.RECIPES[first_aid]}
        self.assertNotIn(3276, named)
        for value in range(1, 76):
            recipe = craft.recipe_for(first_aid, value)
            if recipe is not None:
                self.assertNotEqual(recipe.spell_id, 3276)

    def test_cooking_has_no_reachable_bracket_at_all(self):
        """Every Cooking recipe below the 75 cap needs a Cooking Fire.

        Read off `SkillLineAbility.dbc` joined to `Spell.dbc` from the running
        worldserver: all 181 abilities on skill 185, and every one that
        creates an item and is reachable below 75 carries
        `RequiresSpellFocus = 4`. DriveCraft casts in place, so an entry here
        would sit refused for ever. The table carries none rather than one
        that looks right and produces nothing.
        """
        self.assertEqual(craft.RECIPES[goals.SKILL_IDS["cooking"]], ())
        for value in (1, 50, 51, 75):
            with self.subTest(value=value):
                self.assertIsNone(craft.recipe_for(goals.SKILL_IDS["cooking"], value))

    def test_craft_errand_finds_first_aid_for_a_character_assigned_no_primary_with_recipe(
        self,
    ):
        # Grug: assigned mining + blacksmithing (professions.ROSTER), neither
        # of which has a craft.RECIPES entry, so the primary loop finds
        # nothing - but every character, Grug included, already holds First
        # Aid, so the secondary fallthrough must answer with it.
        spell_id = craft.craft_errand("Grug", {"mining": 8, "first aid": 1})
        self.assertEqual(spell_id, 3275)

    def test_craft_errand_prefers_a_live_primary_recipe_over_a_secondary_one(self):
        # Og: assigned tailoring, which DOES have a verified recipe - that
        # must win over First Aid even though Og also holds First Aid, same
        # "one craft_spell at a time" contract craft_errand always had.
        spell_id = craft.craft_errand(
            "Og", {"tailoring": 1, "first aid": 1, "cooking": 1}
        )
        self.assertEqual(spell_id, 2963)

    def test_craft_errand_zero_for_first_aid_not_yet_learned(self):
        # A value of 0 means the trainer errand has not landed yet, the same
        # rule craft_errand already holds for a primary trade - never invent
        # a recipe for a skill nobody has actually trained.
        spell_id = craft.craft_errand("Grug", {"mining": 8, "first aid": 0})
        self.assertEqual(spell_id, 0)

    def test_craft_errand_is_silent_once_first_aid_is_past_its_grey(self):
        """There is nothing to fall through TO, and that is the honest answer.

        This test used to assert a fall-through to Charred Wolf Meat (2538).
        That recipe needed a Cooking Fire the system cannot light, so the
        fall-through delivered a permanently refused cast dressed as progress.
        0 means "no standing craft errand" - the schema's own sentinel - and a
        caller that wants to know WHY asks
        `professions.SECONDARY_BLOCKED['cooking']`.
        """
        spell_id = craft.craft_errand(
            "Grug", {"mining": 8, "first aid": 60, "cooking": 1}
        )
        self.assertEqual(spell_id, 0)

    def test_cooking_never_shadows_first_aid_in_the_secondary_fallthrough(self):
        """The ordering defect the Cooking entry was hiding (infra#3614).

        `craft_errand` walks `sorted(professions.SECONDARY)`, and "cooking"
        sorts before "first aid". So for as long as Cooking carried a bracket
        at value 1, every character reaching the secondary fall-through got
        the focus-gated Cooking recipe and First Aid was never consulted at
        all - the castable recipe was shadowed by the inert one.
        """
        self.assertLess(
            sorted(professions.SECONDARY).index("cooking"),
            sorted(professions.SECONDARY).index("first aid"),
            "if this ever stops being true the shadowing below changes shape",
        )
        spell_id = craft.craft_errand(
            "Grug", {"mining": 8, "first aid": 1, "cooking": 1}
        )
        self.assertEqual(spell_id, 3275)


class RecipeTableDisciplineTests(unittest.TestCase):
    """The module's own stated rule: one verified entry beats five guessed
    ones. This suite is what keeps a future edit honest about that."""

    def test_every_recipe_has_a_positive_spell_id(self):
        for recipes in craft.RECIPES.values():
            for recipe in recipes:
                self.assertGreater(recipe.spell_id, 0)

    def test_every_recipe_key_is_a_real_profession_skill(self):
        # CRAFTING (a primary, slot-costing trade) and SECONDARY (First Aid /
        # Cooking / Fishing, free and held by everyone) are the two kinds of
        # skill `craft_errand` answers for, and GATHERING joined them as a
        # RECIPES key in infra#3748 - not as a third thing `craft_errand`
        # considers (it still does not; see `test_craft_errand_never_answers_
        # with_a_smelt` below) but because this table is keyed by SKILL ID
        # rather than by trade class, and Mining's smelt brackets are real
        # castable recipes on a gathering skill. A key outside all three is a
        # typo, not a new profession.
        real_ids = {
            goals.SKILL_IDS[name]
            for name in (
                professions.CRAFTING | professions.SECONDARY | professions.GATHERING
            )
            if name in goals.SKILL_IDS
        }
        for skill_id in craft.RECIPES:
            self.assertIn(skill_id, real_ids)

    def test_the_only_gathering_key_is_the_one_with_a_walk_behind_it(self):
        """Widening the key rule above must not become a general permission.

        Herbalism and Skinning have no craftable recipe of their own and no
        focus object anybody walks to, so a bracket appearing under either
        would be the key rule being read as "any profession may have recipes"
        rather than as the one deliberate addition it is."""
        gathering_keys = {
            skill_id
            for skill_id in craft.RECIPES
            if skill_id
            in {
                goals.SKILL_IDS[n]
                for n in professions.GATHERING
                if n in goals.SKILL_IDS
            }
        }
        self.assertEqual(gathering_keys, {goals.SKILL_IDS["mining"]})

    def test_brackets_do_not_overlap_within_one_skill(self):
        for recipes in craft.RECIPES.values():
            ordered = sorted(recipes, key=lambda r: r.min_skill)
            for a, b in zip(ordered, ordered[1:]):
                self.assertLess(a.max_skill, b.min_skill)


class TheModeConstant(unittest.TestCase):
    def test_it_matches_the_vocabulary(self):
        import jobs

        self.assertEqual(craft.MODE, "craft")
        self.assertIn(craft.MODE, jobs.MODES)
        self.assertIn(craft.MODE, jobs.IMPLEMENTED)


class NoForecastOfTheWorldserversAnswer(unittest.TestCase):
    """infra#3695. This pins an ABSENCE, deliberately, because the thing it
    forbids is the thing two agents reached for on the same afternoon.

    A `craft.readiness()` that asked whether each character knows its recipe -
    reading `character_spell` - was written, tested, and was WRONG: every row
    said nobody knew anything while Ugga was crafting Minor Healing Potions
    (2330) seven times over. mod-playerbots grants recipes at runtime and
    `Player::_SaveSpells` never persists them, so the saved tables are partial
    in exactly the direction that turns a guard into a false refusal.

    `Player::HasSpell` is what DriveCraft gates on and it reads live memory.
    Python cannot see that, so Python must not pretend to predict it. If a
    readiness answer is ever wanted here it has to consume DriveCraft's own
    recorded outcome, not forecast it.
    """

    def test_craft_exposes_no_readiness_predicate(self):
        self.assertFalse(
            hasattr(craft, "readiness"),
            "craft.readiness() forecasts DriveCraft's HasSpell check from "
            "saved tables that omit runtime-granted recipes - see this class's "
            "docstring and craft.py's header before re-adding it",
        )

    def test_the_module_records_why(self):
        import inspect

        source = inspect.getsource(craft)
        self.assertIn("3695", source)
        self.assertIn("_SaveSpells", source)


class SpellFocusTests(unittest.TestCase):
    """A recipe may need a spell focus only if something here walks to it.

    WHAT THIS CLASS USED TO ASSERT, AND WHY IT CHANGED (infra#3747 ->
    infra#3748). infra#3747 added `Recipe.focus` and held the WHOLE table to
    `focus == 0`, because at that moment nothing anywhere could stand a
    character next to a focus object: DriveCraft casts in place, CheckCast
    refuses a focus-gated recipe with SPELL_FAILED_REQUIRES_SPELL_FOCUS, and
    mod-overseer neither clears the errand on that refusal nor tells it from a
    cooldown - it logs a bare numeric SpellCastResult at INFO and retries every
    twenty seconds. So a focus-gated entry would have sat in the table looking
    correct and produced nothing for ever, while the log read like a transient.
    "Zero" was the right rule while the true answer was "none of them".

    infra#3748 SHIPPED THE WALK FOR EXACTLY ONE OF THE THREE. `bridge._forge_once`
    stands the leader inside a spawned Forge's focus before a smelt is cast, so
    `focus = 3` is now honourable. The rule therefore becomes "zero, or a focus
    id something actually walks to" - `craft.FOCUS_AIMS` - rather than either
    "zero for ever" (which would refuse the fix) or "any non-zero is fine"
    (which would let infra#3617's Anvil-gated Blacksmithing recipes in, and
    those still have no walk AND still need a Blacksmith Hammer equipped).

    THE SECOND TEST IS WHAT STOPS `FOCUS_AIMS` BECOMING A LIST OF INTENTIONS.
    A mapping that merely CLAIMS a walk exists would re-open the whole hole in
    one line, so every key is held to a `travel` helper and a `bridge` pass
    that really exist.
    """

    def test_every_declared_focus_matches_the_worldservers_own_answer(self):
        """THE GUARD THAT IS NOT VACUOUS, and the one this class used to lack.

        `assertEqual(recipe.focus, 0)` against a field that DEFAULTS to 0 is a
        comparison of the declared value with itself. This compares it with
        `Spell.dbc`'s `RequiresSpellFocus` instead, so a wrong declaration
        fails whether it was written as 0, left at its default, or typed as the
        wrong non-zero id."""
        for skill_id, recipes in craft.RECIPES.items():
            for recipe in recipes:
                with self.subTest(skill=skill_id, recipe=recipe.name):
                    self.assertIn(
                        recipe.spell_id,
                        MEASURED_FOCUS,
                        f"{recipe.name} (spell {recipe.spell_id}) is in "
                        "RECIPES with no measured RequiresSpellFocus. Pull "
                        "Spell.dbc from the worldserver pod and run "
                        "tools/spell_focus_from_dbc.py - a recipe whose focus "
                        "nobody looked up is how eleven Engineering brackets "
                        "sat refused for their whole life (infra#3760).",
                    )
                    self.assertEqual(
                        recipe.focus,
                        MEASURED_FOCUS[recipe.spell_id],
                        f"{recipe.name} (spell {recipe.spell_id}) declares "
                        f"focus={recipe.focus} and the worldserver's own "
                        f"Spell.dbc says {MEASURED_FOCUS[recipe.spell_id]}. "
                        "The declaration is what `craft.focus_for` hands the "
                        "forge pass, so a wrong one either sends nobody to a "
                        "focus they need or sends them to the wrong object.",
                    )

    def test_the_measured_table_has_no_entries_for_recipes_that_are_gone(self):
        """A projection that outlives its subject is a projection nobody is
        reading. Kept exactly in step so the assertion above cannot be
        satisfied by a stale row."""
        named = {
            recipe.spell_id for recipes in craft.RECIPES.values() for recipe in recipes
        }
        self.assertEqual(set(MEASURED_FOCUS), named)

    def test_a_focus_gated_recipe_without_a_walk_is_a_named_counted_debt(self):
        """The other half: a declaration can be HONEST and still name a focus
        nothing stands a character in, which is the eleven Engineering entries
        infra#3760 is filed for. They stay in the table - removing them would
        hide the gap rather than close it - but the set is pinned to exactly
        those eleven, so a twelfth cannot be added without a walk."""
        stranded = {
            recipe.spell_id
            for recipes in craft.RECIPES.values()
            for recipe in recipes
            if recipe.focus and recipe.focus not in craft.FOCUS_AIMS
        }
        self.assertEqual(
            stranded,
            FOCUS_WITHOUT_A_WALK,
            "a recipe declaring a focus nothing walks to sits refused on every "
            "poll for ever, logged by DriveCraft as a bare SpellCastResult "
            "that reads like a cooldown. Land the aim and add the focus id to "
            "craft.FOCUS_AIMS in the same change.",
        )

    def test_the_stranded_ones_are_all_the_anvil_and_all_engineering(self):
        """Says what the debt IS, so the number above is not just a number:
        one focus object, one profession, one issue."""
        stranded = {
            recipe.spell_id: recipe.focus
            for recipes in craft.RECIPES.values()
            for recipe in recipes
            if recipe.focus and recipe.focus not in craft.FOCUS_AIMS
        }
        self.assertEqual(set(stranded.values()), {1})  # Anvil, and only Anvil
        engineering = {
            r.spell_id for r in craft.RECIPES[goals.SKILL_IDS["engineering"]]
        }
        self.assertLessEqual(set(stranded), engineering)

    def test_an_anvil_gated_recipe_is_still_refused(self):
        """infra#3617's half stays fenced. Anvil is focus 1 and there is no
        anvil walk, so widening the rule above for the forge must not have
        quietly admitted every other focus object too."""
        self.assertNotIn(1, craft.FOCUS_AIMS)  # Anvil
        self.assertNotIn(2, craft.FOCUS_AIMS)  # Loom

    def test_the_forge_aim_is_not_merely_claimed(self):
        # FOCUS_AIMS says something walks to focus 3. These are the two halves
        # of that claim: the pure aim builder, and the bridge pass that writes
        # what it returns. Imported by name rather than by grepping source, so
        # a rename breaks this instead of silently passing.
        self.assertEqual(set(craft.FOCUS_AIMS), {3})
        self.assertEqual(craft.FOCUS_AIMS[3], "forge")
        self.assertEqual(travel.FORGE_FOCUS_ID, 3)
        self.assertTrue(callable(travel.forge_aim))
        self.assertTrue(callable(travel.within_focus))

    def test_a_smelt_spell_may_only_appear_under_mining_with_the_forge_focus(self):
        """The smelt chain, read off the running worldserver's Spell.dbc.

        infra#3747's version of this refused every one of these ids outright.
        Now that one of them ships, the pin has to say something sharper than
        "no smelts": a smelt is Forge-gated and sits on skill line 186, so an
        entry that named one under Engineering, or named one with `focus` left
        at its default, would be a recipe DriveCraft could never cast and this
        is where that is caught. 2659 is Smelt Bronze, NOT Smelt Copper as
        infra#3738 states; Smelt Copper is 2657."""
        smelt_spells = {
            2657: "Smelt Copper",
            2658: "Smelt Silver",
            2659: "Smelt Bronze",
            3304: "Smelt Tin",
            3307: "Smelt Iron",
            3308: "Smelt Gold",
            3569: "Smelt Steel",
            10097: "Smelt Mithril",
            10098: "Smelt Truesilver",
            16153: "Smelt Thorium",
        }
        for skill_id, recipes in craft.RECIPES.items():
            for recipe in recipes:
                if recipe.spell_id not in smelt_spells:
                    continue
                with self.subTest(recipe=recipe.name):
                    self.assertEqual(
                        skill_id,
                        goals.SKILL_IDS["mining"],
                        "%s is a Mining ability (SkillLineAbility.dbc skill "
                        "line 186) and cannot be cast off any other skill"
                        % recipe.name,
                    )
                    self.assertEqual(
                        recipe.focus,
                        3,
                        "%s carries RequiresSpellFocus = 3 (Forge) in "
                        "Spell.dbc; declaring anything else here would skip "
                        "the walk" % recipe.name,
                    )

    def test_the_trainer_taught_smelts_are_deliberately_absent(self):
        """Only Smelt Copper is `AcquireMethod = 1` - granted with Apprentice
        Mining. The other nine are taught by a Mining trainer, and nothing in
        this repo sends anybody to one for an individual recipe, so naming one
        would make DriveCraft drop the errand with its "does not know the
        recipe ... a planner bug" WARN. Bronze and Steel are absent for a
        different reason again: both consume two smelted bars and a character
        holds one craft_spell, so neither can ever be stocked."""
        named = {
            recipe.spell_id for recipes in craft.RECIPES.values() for recipe in recipes
        }
        for spell in (2658, 2659, 3304, 3307, 3308, 3569, 10097, 10098, 16153):
            with self.subTest(spell=spell):
                self.assertNotIn(spell, named)
        self.assertIn(2657, named)

    def test_craft_errand_never_answers_with_a_smelt(self):
        """The two readers stay separate.

        `professions.assigned` lists both of the family's miners with mining
        FIRST - Grug ("mining", "blacksmithing"), Grog ("mining",
        "engineering") - so had the Mining bracket been admitted by widening
        `craft_errand`'s own loop instead of adding `smelt_errand` beside it,
        the first matching bracket would have become the smelt for both of
        them permanently and their crafting trades would have stopped the day
        it shipped."""
        skills = {"mining": 8, "blacksmithing": 1}
        self.assertEqual(craft.craft_errand("Grug", skills), 2660)
        self.assertEqual(craft.smelt_errand("Grug", skills), 2657)

    def test_smelt_errand_is_zero_for_a_character_with_no_gathering_trade(self):
        self.assertEqual(craft.smelt_errand("Og", {"tailoring": 1}), 0)

    def test_smelt_errand_is_zero_above_the_one_shipped_bracket(self):
        """Mining 70 is grey for Smelt Copper and the next bracket is
        trainer-gated and deliberately unshipped, so this answers nothing
        rather than naming a spell the character does not hold."""
        self.assertEqual(craft.smelt_errand("Grug", {"mining": 70}), 0)
        self.assertEqual(craft.smelt_errand("Grug", {"mining": 69}), 2657)

    def test_focus_for_reads_the_table_so_callers_do_not(self):
        self.assertEqual(craft.focus_for(2657), 3)
        self.assertEqual(craft.focus_for(2660), 0)  # Rough Sharpening Stone
        self.assertEqual(craft.focus_for(0), 0)
        self.assertEqual(craft.focus_for(999999), 0)  # a spell this table lost

    def test_no_cooking_recipe_needs_a_fire(self):
        """The sibling of the smelt refusal, for focus 4 (infra#3614).

        WHY THIS EXISTS SEPARATELY FROM `test_no_recipe_requires_a_spell_focus`
        ABOVE, and it is the hole that let an inert recipe ship. That test
        compares `recipe.focus` against 0 - which is to say it compares the
        declared field against itself. `Recipe.focus` defaults to 0, so an
        entry written before the field existed, or one added by someone who
        never looked the spell up, declares 0 and passes while the worldserver
        refuses it every twenty seconds. Charred Wolf Meat (2538) sat in this
        table in exactly that state: declared 0, `Spell.dbc` says 4.

        So this test pins ids, the way `test_no_recipe_is_a_smelt_spell` does,
        because an id is a fact a future edit cannot accidentally re-declare.
        Every value below was read off `Spell.dbc` and `SpellFocusObject.dbc`
        pulled from the running worldserver, with the parse proved first
        against this table's own anchor (2963 -> Reagent[0]=2589,
        ReagentCount[0]=2).

        37836 (Spice Bread) is on the list deliberately. infra#3732 called it
        "the cheapest real point of secondary progress available" because the
        family demonstrably owns it - and it is focus 4 like the rest, with a
        yellow/grey of 30/40 that is shorter than the Charred Wolf Meat it
        would have replaced. It is a worse version of the same mistake, and
        this test is what says no to it.
        """
        fire_spells = {
            2538: "Charred Wolf Meat",
            2540: "Roasted Boar Meat",
            3370: "Crocolisk Steak",
            3371: "Blood Sausage",
            3372: "Murloc Fin Soup",
            3373: "Crocolisk Gumbo",
            3376: "Curiously Tasty Omelet",
            3377: "Gooey Spider Cake",
            3397: "Big Bear Steak",
            3398: "Hot Lion Chops",
            6412: "Kaldorei Spider Kabob",
            6413: "Scorpid Surprise",
            6414: "Roasted Kodo Meat",
            6415: "Fillet of Frenzy",
            6416: "Strider Stew",
            6417: "Dig Rat Stew",
            7751: "Brilliant Smallfish",
            7752: "Slitherskin Mackerel",
            37836: "Spice Bread",
        }
        named = {
            recipe.spell_id for recipes in craft.RECIPES.values() for recipe in recipes
        }
        clash = named & set(fire_spells)
        self.assertFalse(
            clash,
            "RECIPES names %s, which require a Cooking Fire "
            "(RequiresSpellFocus = 4, SpellFocusObject.dbc id 4). Nothing in "
            "this system lights one. See craft.py's COOKING comment for the "
            "single cast (spell 818, gameobject 29784, ten-yard radius) that "
            "would."
            % sorted("%d (%s)" % (spell, fire_spells[spell]) for spell in clash),
        )

    def test_the_module_records_the_forge_finding(self):
        # The measurements behind this are the expensive part of infra#3738,
        # infra#3747 and infra#3748, and the reason none of it will be
        # re-litigated from a wiki.
        import inspect

        source = inspect.getsource(craft)
        self.assertIn("3738", source)
        self.assertIn("3748", source)
        self.assertIn("RequiresSpellFocus", source)
        self.assertIn("2657", source)
        # The field-index correction, which is the trap the next reader
        # re-deriving these facts from Spell.dbc will otherwise fall into.
        self.assertIn("field 18", source)
        self.assertIn("AcquireMethod", source)

    def test_the_module_records_the_cooking_fire_finding(self):
        # Same reason as the forge finding above: the campfire measurement
        # (spell 818 -> gameobject 29784, type 8 / Data0 4 / Data1 10) is the
        # expensive part of infra#3614, and it is what stops the next reader
        # concluding that Cooking is merely missing a bracket.
        import inspect

        source = inspect.getsource(craft)
        self.assertIn("818", source)
        self.assertIn("29784", source)
        self.assertIn("Cooking Fire", source)


class ColourBandTests(unittest.TestCase):
    """EVERY BRACKET EDGE AGAINST THE REALM'S OWN NUMBER, which is the check
    that did not exist while ten of sixty-one entries were wrong.

    `test_brackets_do_not_overlap_within_one_skill` already holds this table's
    INTERNAL consistency - no two entries claiming one point - and it passed
    happily throughout, because a bracket can be perfectly tidy with respect to
    its neighbours and still name a value the worldserver will not act on.
    Tidiness is a property of the table; a colour band is a property of the
    realm, and only the second one decides whether a character's skill moves.
    """

    def test_no_bracket_reaches_its_own_grey_value(self):
        """THE SILENT HALF. At or past TrivialSkillLineRankHigh the core rolls
        no skill-up at all, so these casts consume reagents, produce the item,
        log nothing unusual, and grant nothing. Og sat at Tailoring 50 against
        Bolt of Linen Cloth's grey of 50 and had 151 bolts in his bags to show
        for it."""
        for skill_id, recipes in craft.RECIPES.items():
            for recipe in recipes:
                _req, _yellow, grey = MEASURED_BANDS[recipe.spell_id]
                with self.subTest(skill=skill_id, recipe=recipe.name):
                    self.assertLess(
                        recipe.max_skill,
                        grey,
                        "%s (spell %d) runs to %d against a grey value of %d - "
                        "the last %d point(s) of that bracket cast for nothing"
                        % (
                            recipe.name,
                            recipe.spell_id,
                            recipe.max_skill,
                            grey,
                            recipe.max_skill - grey + 1,
                        ),
                    )

    def test_no_bracket_starts_below_its_own_learn_floor(self):
        """THE LOUD HALF, which was still missed for a year. Below
        MinSkillLineRank the character cannot hold the spell, so DriveCraft
        drops the errand and logs 'a planner bug' - on a twenty-second loop,
        into a log nobody reads. Coarse Sharpening Stone claimed 65 against a
        floor of 75 and Lesser Healing Potion claimed 60 against 80."""
        for skill_id, recipes in craft.RECIPES.items():
            for recipe in recipes:
                req, _yellow, _grey = MEASURED_BANDS[recipe.spell_id]
                with self.subTest(skill=skill_id, recipe=recipe.name):
                    self.assertGreaterEqual(
                        recipe.min_skill,
                        req,
                        "%s (spell %d) starts at %d but cannot be learned "
                        "until %d"
                        % (recipe.name, recipe.spell_id, recipe.min_skill, req),
                    )

    def test_the_projection_is_kept_exactly_in_step_with_the_table(self):
        """Same rule as MEASURED_FOCUS: a projection that outlives its subject
        is one nobody is reading, and a missing row would make both assertions
        above raise KeyError rather than fail with a sentence."""
        named = {
            recipe.spell_id for recipes in craft.RECIPES.values() for recipe in recipes
        }
        self.assertEqual(set(MEASURED_BANDS), named)

    def test_the_generator_exists_and_asserts_its_anchors(self):
        """The projection is only as good as the parse behind it, and this
        file cannot re-derive it (CI has no cluster and Spell.dbc is 48MB).
        So pin that the tool is present and still anchored - a generator that
        stopped checking 2963/2657/3275 could emit plausible nonsense."""
        tool = (
            pathlib.Path(__file__).resolve().parents[1]
            / "tools"
            / "spell_bands_from_dbc.py"
        )
        self.assertTrue(tool.exists(), "tools/spell_bands_from_dbc.py is gone")
        source = tool.read_text(encoding="utf-8", errors="replace")
        for anchor in ("2963", "2657", "3275", "3276"):
            self.assertIn(anchor, source)
        # the field-offset trap and the two-ability-rows trap, both recorded
        self.assertIn("18", source)
        self.assertIn("0x20", source)

    def test_the_module_records_the_colour_band_finding(self):
        """The expensive part of this pass is the measurement, not the ten
        edits, and craft.py is where the next reader will look."""
        import inspect

        source = inspect.getsource(craft)
        self.assertIn("TrivialSkillLineRankHigh", source)
        self.assertIn("MinSkillLineRank", source)
        self.assertIn("COLOUR BANDS", source)


if __name__ == "__main__":
    unittest.main()
