"""Print the SQL that puts a family on a world's `overseer_roster`.

    python3 tools/seed_roster.py --family dev

WHY A PRINTER AND NOT A WRITER. The live world's roster is written by the
Discord bridge, on a loop, from `bonds.FAMILY` - and the bridge is rendered at
`replicas: 0` in the dev world on purpose (a second gateway session on one bot
token answers the live #wow channel). So dev's roster has no writer, and until
it has one somebody has to seed it by hand.

That somebody needs a database password, and this script deliberately does not
want one. It emits SQL on stdout and connects to nothing, which means it can be
READ before it is run, diffed between two runs, and pasted into a review. The
operator supplies the credential at the point of use:

    python3 tools/seed_roster.py --family dev \\
      | kubectl -n wow-dev exec -i mysql-0 -- \\
          bash -c 'mysql -uroot -p"$MYSQL_ROOT_PASSWORD" acore_characters'

WHAT IT WILL NOT DO, AND WHY EACH REFUSAL IS DELIBERATE.

  It never writes `drive_quest`. ONLY ONE CHARACTER TRAVELS - the traveller -
  and the followers get `nc -new rpg` stripped on purpose, because `new rpg`
  acts at relevance 3.0-11.0 against follow's 1.0 and a follower given both
  wanders off every tick. Aiming all five scatters the family across 937 yards
  (infra#2812); it happened on 2026-08-23 and one character walked into a
  lethal zone and died. `drive_quest` is a decision the council makes and the
  bridge persists, per-quest, to one row. A seed script has no business having
  an opinion about it, so it leaves the column at its default of 0, which the
  module reads as "no aim" and which degrades to leader-only travel.

  It never writes `learn_skill` / `unlearn_skill` / `unlearn_max`. Those are a
  standing ERRAND - go to this trainer and do this thing - and an errand seeded
  from a table rather than observed from `character_skills` is an instruction
  to buy something the character may already own. `professions` IS written,
  because that column is the module's PERMISSION rather than an instruction:
  the module will only learn a skill named there and will never unlearn one
  that is, so seeding it is what makes a later wrong errand harmless.

  It never re-enables a disabled row. `INSERT IGNORE`, exactly as
  `bridge._ensure_roster` does: parking a character is a decision somebody made
  by hand, and a seed that silently undid it would make that decision
  unmakeable.

WHAT IT DOES NOT KNOW ABOUT. Whether the characters exist. A roster row naming
a character that was never created is inert - the module looks for a name and
finds nothing - so this is safe to run early, and running it is not evidence
that anybody is in the world. Characters cannot be created server-side at all
(`Player::Create` is only wired into `RandomPlayerbotFactory`, which picks its
own race and name); they are made in the game client, by a person. See
../../../oke/manifests/wow-dev/README.md.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

import cast  # noqa: E402


def _quote(value: str) -> str:
    """A MySQL string literal. Backslash and quote escaped, nothing else.

    Every value that reaches this function is a name or a skill-id list built
    from tables in this repository - never from a request, a database row or an
    argument - so this is defence against a typo in those tables rather than
    against an attacker. It is here anyway because the output is executed as
    SQL, and "the inputs are all trusted" is a sentence that stops being true
    without anybody editing this file.
    """
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def statements(which: str) -> list[str]:
    """The SQL, as a list of statements, for the family `which` names.

    Imported INSIDE the function and after the environment is set, because
    `bonds.FAMILY` and `professions.ROSTER` are resolved at import time from
    `OVERSEER_FAMILY` - which is exactly how the bridge and the map resolve
    them. Going through the same door means this tool cannot produce a roster
    that those two processes would disagree with.
    """
    os.environ[cast.ENV_VAR] = which
    import bonds  # noqa: PLC0415
    import professions  # noqa: PLC0415

    if cast.selected() != which:
        raise SystemExit(f"unknown family set {which!r}")

    family = bonds.FAMILY
    head = bonds.head_of_family()
    order = bonds.speaking_order(family)

    out = [
        f"-- overseer_roster seed for the {which!r} family: " + ", ".join(order),
        "-- Generated by production/scripts/wow-overseer/tools/seed_roster.py.",
        "-- Contains no credentials. Safe to read, diff and review before running.",
        "",
        "-- 1. The rows. INSERT IGNORE, so a row parked by hand stays parked.",
    ]
    for name in order:
        note = f"{which} family - {family[name].role}"
        out.append(
            "INSERT IGNORE INTO overseer_roster (name, note) VALUES "  # noqa: S608 - this script's whole PRODUCT is SQL text; every value is a name or a skill-id from tables in this repo, quoted by _quote, and it connects to no database
            f"({_quote(name)}, {_quote(note)});"
        )

    out += [
        "",
        "-- 2. Talent trees. The DBC tabpage each character spends points in,",
        "--    from bonds.FAMILY - the tank tanks and the healer heals because",
        "--    of who they are, not because a random roll went that way.",
    ]
    # Emitted in the family's own speaking order, like every other block here,
    # and NOT sorted by name. Alphabetical would order the two worlds
    # differently - Bork first in one, Durn first in the other - which makes
    # the live and dev seeds impossible to diff against each other, and that
    # diff is the only check anybody has that the two worlds are being set up
    # the same way.
    tabs = bonds.spec_tabs()
    for name in (n for n in order if n in tabs):
        tab = tabs[name]
        out.append(
            f"UPDATE overseer_roster SET spec_tab = {int(tab)} "  # noqa: S608 - this script's whole PRODUCT is SQL text; every value is a name or a skill-id from tables in this repo, quoted by _quote, and it connects to no database
            f"WHERE name = {_quote(name)};"
        )

    out += [
        "",
        "-- 3. Trade PERMISSIONS - not errands. The module will only ever learn",
        "--    a skill named here and will never unlearn one that is, which is",
        "--    what makes a later wrong instruction harmless.",
    ]
    for name in order:
        ids = professions.wanted_ids(name)
        if ids:
            out.append(
                f"UPDATE overseer_roster SET professions = {_quote(ids)} "  # noqa: S608 - this script's whole PRODUCT is SQL text; every value is a name or a skill-id from tables in this repo, quoted by _quote, and it connects to no database
                f"WHERE name = {_quote(name)};"
            )

    out += [
        "",
        "-- 4. Who leads. Written as ONE statement over the whole table, which",
        "--    is bridge._mark_lead's own shape: a party has one leader, and two",
        "--    rows claiming it is a state no separate UPDATE can rule out.",
        "--    NOTE this clears `lead` from anyone else already on the roster.",
        f"UPDATE overseer_roster SET `lead` = IF(name = {_quote(head)}, 1, 0);",  # noqa: S608 - this script's whole PRODUCT is SQL text; every value is a name or a skill-id from tables in this repo, quoted by _quote, and it connects to no database
        "",
        "-- 5. What you should see. `drive_quest` is 0 for everyone and stays",
        "--    that way here: only the traveller is ever aimed (infra#2812).",
        "SELECT name, enabled, `lead`, spec_tab, professions, drive_quest",
        "  FROM overseer_roster ORDER BY `lead` DESC, name;",
    ]
    return out


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--family",
        default=cast.DEV,
        choices=(cast.LIVE, cast.DEV),
        help="which family to seed (default: %(default)s). `live` is offered "
        "so the live roster can be diffed against what this would write, "
        "never because the live world needs seeding - the bridge does "
        "that on a loop.",
    )
    args = parser.parse_args(argv)
    print("\n".join(statements(args.family)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
